// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: apis_servicio.proto

package dbgsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ApisService_CrearApi_FullMethodName         = "/dbgs.v1.ApisService/CrearApi"
	ApisService_ListarApis_FullMethodName       = "/dbgs.v1.ApisService/ListarApis"
	ApisService_ObtenerApi_FullMethodName       = "/dbgs.v1.ApisService/ObtenerApi"
	ApisService_CambiarEstadoApi_FullMethodName = "/dbgs.v1.ApisService/CambiarEstadoApi"
	ApisService_EliminarApi_FullMethodName      = "/dbgs.v1.ApisService/EliminarApi"
)

// ApisServiceClient is the client API for ApisService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Servicio gRPC para la publicación y administración de APIs de servicio
// (APIs públicas de solo lectura sobre tablas/conexiones registradas).
type ApisServiceClient interface {
	CrearApi(ctx context.Context, in *CrearApiRequest, opts ...grpc.CallOption) (*ApiResponse, error)
	ListarApis(ctx context.Context, in *ListarApisRequest, opts ...grpc.CallOption) (*ListarApisResponse, error)
	ObtenerApi(ctx context.Context, in *ObtenerApiRequest, opts ...grpc.CallOption) (*ApiResponse, error)
	CambiarEstadoApi(ctx context.Context, in *CambiarEstadoApiRequest, opts ...grpc.CallOption) (*ApiResponse, error)
	EliminarApi(ctx context.Context, in *EliminarApiRequest, opts ...grpc.CallOption) (*EliminarApiResponse, error)
}

type apisServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewApisServiceClient(cc grpc.ClientConnInterface) ApisServiceClient {
	return &apisServiceClient{cc}
}

func (c *apisServiceClient) CrearApi(ctx context.Context, in *CrearApiRequest, opts ...grpc.CallOption) (*ApiResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponse)
	err := c.cc.Invoke(ctx, ApisService_CrearApi_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apisServiceClient) ListarApis(ctx context.Context, in *ListarApisRequest, opts ...grpc.CallOption) (*ListarApisResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListarApisResponse)
	err := c.cc.Invoke(ctx, ApisService_ListarApis_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apisServiceClient) ObtenerApi(ctx context.Context, in *ObtenerApiRequest, opts ...grpc.CallOption) (*ApiResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponse)
	err := c.cc.Invoke(ctx, ApisService_ObtenerApi_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apisServiceClient) CambiarEstadoApi(ctx context.Context, in *CambiarEstadoApiRequest, opts ...grpc.CallOption) (*ApiResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponse)
	err := c.cc.Invoke(ctx, ApisService_CambiarEstadoApi_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apisServiceClient) EliminarApi(ctx context.Context, in *EliminarApiRequest, opts ...grpc.CallOption) (*EliminarApiResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EliminarApiResponse)
	err := c.cc.Invoke(ctx, ApisService_EliminarApi_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ApisServiceServer is the server API for ApisService service.
// All implementations must embed UnimplementedApisServiceServer
// for forward compatibility.
//
// Servicio gRPC para la publicación y administración de APIs de servicio
// (APIs públicas de solo lectura sobre tablas/conexiones registradas).
type ApisServiceServer interface {
	CrearApi(context.Context, *CrearApiRequest) (*ApiResponse, error)
	ListarApis(context.Context, *ListarApisRequest) (*ListarApisResponse, error)
	ObtenerApi(context.Context, *ObtenerApiRequest) (*ApiResponse, error)
	CambiarEstadoApi(context.Context, *CambiarEstadoApiRequest) (*ApiResponse, error)
	EliminarApi(context.Context, *EliminarApiRequest) (*EliminarApiResponse, error)
	mustEmbedUnimplementedApisServiceServer()
}

// UnimplementedApisServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedApisServiceServer struct{}

func (UnimplementedApisServiceServer) CrearApi(context.Context, *CrearApiRequest) (*ApiResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CrearApi not implemented")
}
func (UnimplementedApisServiceServer) ListarApis(context.Context, *ListarApisRequest) (*ListarApisResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListarApis not implemented")
}
func (UnimplementedApisServiceServer) ObtenerApi(context.Context, *ObtenerApiRequest) (*ApiResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ObtenerApi not implemented")
}
func (UnimplementedApisServiceServer) CambiarEstadoApi(context.Context, *CambiarEstadoApiRequest) (*ApiResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CambiarEstadoApi not implemented")
}
func (UnimplementedApisServiceServer) EliminarApi(context.Context, *EliminarApiRequest) (*EliminarApiResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EliminarApi not implemented")
}
func (UnimplementedApisServiceServer) mustEmbedUnimplementedApisServiceServer() {}
func (UnimplementedApisServiceServer) testEmbeddedByValue()                     {}

// UnsafeApisServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ApisServiceServer will
// result in compilation errors.
type UnsafeApisServiceServer interface {
	mustEmbedUnimplementedApisServiceServer()
}

func RegisterApisServiceServer(s grpc.ServiceRegistrar, srv ApisServiceServer) {
	// If the following call panics, it indicates UnimplementedApisServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ApisService_ServiceDesc, srv)
}

func _ApisService_CrearApi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CrearApiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApisServiceServer).CrearApi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApisService_CrearApi_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApisServiceServer).CrearApi(ctx, req.(*CrearApiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApisService_ListarApis_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListarApisRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApisServiceServer).ListarApis(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApisService_ListarApis_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApisServiceServer).ListarApis(ctx, req.(*ListarApisRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApisService_ObtenerApi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ObtenerApiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApisServiceServer).ObtenerApi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApisService_ObtenerApi_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApisServiceServer).ObtenerApi(ctx, req.(*ObtenerApiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApisService_CambiarEstadoApi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CambiarEstadoApiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApisServiceServer).CambiarEstadoApi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApisService_CambiarEstadoApi_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApisServiceServer).CambiarEstadoApi(ctx, req.(*CambiarEstadoApiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApisService_EliminarApi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EliminarApiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApisServiceServer).EliminarApi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApisService_EliminarApi_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApisServiceServer).EliminarApi(ctx, req.(*EliminarApiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ApisService_ServiceDesc is the grpc.ServiceDesc for ApisService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ApisService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dbgs.v1.ApisService",
	HandlerType: (*ApisServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CrearApi",
			Handler:    _ApisService_CrearApi_Handler,
		},
		{
			MethodName: "ListarApis",
			Handler:    _ApisService_ListarApis_Handler,
		},
		{
			MethodName: "ObtenerApi",
			Handler:    _ApisService_ObtenerApi_Handler,
		},
		{
			MethodName: "CambiarEstadoApi",
			Handler:    _ApisService_CambiarEstadoApi_Handler,
		},
		{
			MethodName: "EliminarApi",
			Handler:    _ApisService_EliminarApi_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "apis_servicio.proto",
}
