// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: auditoria_servicio.proto

package dbgsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuditoriaService_ConsultarEventos_FullMethodName = "/dbgs.v1.AuditoriaService/ConsultarEventos"
)

// AuditoriaServiceClient is the client API for AuditoriaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Servicio gRPC de SOLO LECTURA para la consulta de eventos de auditoría.
// La escritura ocurre exclusivamente a nivel de motor (triggers fn_auditar_cambios),
// nunca por petición del cliente, para evitar la falsificación de trazas.
type AuditoriaServiceClient interface {
	// Nota: grpc-gateway parsea automáticamente los Timestamps en Query Strings si se envían en formato RFC3339
	ConsultarEventos(ctx context.Context, in *ConsultarEventosRequest, opts ...grpc.CallOption) (*ConsultarEventosResponse, error)
}

type auditoriaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuditoriaServiceClient(cc grpc.ClientConnInterface) AuditoriaServiceClient {
	return &auditoriaServiceClient{cc}
}

func (c *auditoriaServiceClient) ConsultarEventos(ctx context.Context, in *ConsultarEventosRequest, opts ...grpc.CallOption) (*ConsultarEventosResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConsultarEventosResponse)
	err := c.cc.Invoke(ctx, AuditoriaService_ConsultarEventos_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuditoriaServiceServer is the server API for AuditoriaService service.
// All implementations must embed UnimplementedAuditoriaServiceServer
// for forward compatibility.
//
// Servicio gRPC de SOLO LECTURA para la consulta de eventos de auditoría.
// La escritura ocurre exclusivamente a nivel de motor (triggers fn_auditar_cambios),
// nunca por petición del cliente, para evitar la falsificación de trazas.
type AuditoriaServiceServer interface {
	// Nota: grpc-gateway parsea automáticamente los Timestamps en Query Strings si se envían en formato RFC3339
	ConsultarEventos(context.Context, *ConsultarEventosRequest) (*ConsultarEventosResponse, error)
	mustEmbedUnimplementedAuditoriaServiceServer()
}

// UnimplementedAuditoriaServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuditoriaServiceServer struct{}

func (UnimplementedAuditoriaServiceServer) ConsultarEventos(context.Context, *ConsultarEventosRequest) (*ConsultarEventosResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConsultarEventos not implemented")
}
func (UnimplementedAuditoriaServiceServer) mustEmbedUnimplementedAuditoriaServiceServer() {}
func (UnimplementedAuditoriaServiceServer) testEmbeddedByValue()                          {}

// UnsafeAuditoriaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuditoriaServiceServer will
// result in compilation errors.
type UnsafeAuditoriaServiceServer interface {
	mustEmbedUnimplementedAuditoriaServiceServer()
}

func RegisterAuditoriaServiceServer(s grpc.ServiceRegistrar, srv AuditoriaServiceServer) {
	// If the following call panics, it indicates UnimplementedAuditoriaServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuditoriaService_ServiceDesc, srv)
}

func _AuditoriaService_ConsultarEventos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConsultarEventosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuditoriaServiceServer).ConsultarEventos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuditoriaService_ConsultarEventos_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuditoriaServiceServer).ConsultarEventos(ctx, req.(*ConsultarEventosRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuditoriaService_ServiceDesc is the grpc.ServiceDesc for AuditoriaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuditoriaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dbgs.v1.AuditoriaService",
	HandlerType: (*AuditoriaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ConsultarEventos",
			Handler:    _AuditoriaService_ConsultarEventos_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auditoria_servicio.proto",
}
