// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: catalogos_servicio.proto

package dbgsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CatalogosService_CrearCatalogo_FullMethodName        = "/dbgs.v1.CatalogosService/CrearCatalogo"
	CatalogosService_ObtenerCatalogoPorID_FullMethodName = "/dbgs.v1.CatalogosService/ObtenerCatalogoPorID"
	CatalogosService_ListarCatalogos_FullMethodName      = "/dbgs.v1.CatalogosService/ListarCatalogos"
	CatalogosService_ActualizarCatalogo_FullMethodName   = "/dbgs.v1.CatalogosService/ActualizarCatalogo"
	CatalogosService_EliminarCatalogo_FullMethodName     = "/dbgs.v1.CatalogosService/EliminarCatalogo"
)

// CatalogosServiceClient is the client API for CatalogosService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Servicio gRPC para la gestión de catálogos maestras
type CatalogosServiceClient interface {
	CrearCatalogo(ctx context.Context, in *CrearCatalogoRequest, opts ...grpc.CallOption) (*CatalogoResponse, error)
	// Se utiliza 'get' y el parámetro se extrae automáticamente de la ruta URL usando {id}
	ObtenerCatalogoPorID(ctx context.Context, in *ObtenerCatalogoPorIDRequest, opts ...grpc.CallOption) (*CatalogoResponse, error)
	// Los parámetros de consulta (page_size, solo_activos) se envían como Query Strings (?solo_activos=true)
	ListarCatalogos(ctx context.Context, in *ListarCatalogosRequest, opts ...grpc.CallOption) (*ListarCatalogosResponse, error)
	ActualizarCatalogo(ctx context.Context, in *ActualizarCatalogoRequest, opts ...grpc.CallOption) (*CatalogoResponse, error)
	EliminarCatalogo(ctx context.Context, in *EliminarCatalogoRequest, opts ...grpc.CallOption) (*EliminarCatalogoResponse, error)
}

type catalogosServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCatalogosServiceClient(cc grpc.ClientConnInterface) CatalogosServiceClient {
	return &catalogosServiceClient{cc}
}

func (c *catalogosServiceClient) CrearCatalogo(ctx context.Context, in *CrearCatalogoRequest, opts ...grpc.CallOption) (*CatalogoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CatalogoResponse)
	err := c.cc.Invoke(ctx, CatalogosService_CrearCatalogo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogosServiceClient) ObtenerCatalogoPorID(ctx context.Context, in *ObtenerCatalogoPorIDRequest, opts ...grpc.CallOption) (*CatalogoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CatalogoResponse)
	err := c.cc.Invoke(ctx, CatalogosService_ObtenerCatalogoPorID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogosServiceClient) ListarCatalogos(ctx context.Context, in *ListarCatalogosRequest, opts ...grpc.CallOption) (*ListarCatalogosResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListarCatalogosResponse)
	err := c.cc.Invoke(ctx, CatalogosService_ListarCatalogos_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogosServiceClient) ActualizarCatalogo(ctx context.Context, in *ActualizarCatalogoRequest, opts ...grpc.CallOption) (*CatalogoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CatalogoResponse)
	err := c.cc.Invoke(ctx, CatalogosService_ActualizarCatalogo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogosServiceClient) EliminarCatalogo(ctx context.Context, in *EliminarCatalogoRequest, opts ...grpc.CallOption) (*EliminarCatalogoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EliminarCatalogoResponse)
	err := c.cc.Invoke(ctx, CatalogosService_EliminarCatalogo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CatalogosServiceServer is the server API for CatalogosService service.
// All implementations must embed UnimplementedCatalogosServiceServer
// for forward compatibility.
//
// Servicio gRPC para la gestión de catálogos maestras
type CatalogosServiceServer interface {
	CrearCatalogo(context.Context, *CrearCatalogoRequest) (*CatalogoResponse, error)
	// Se utiliza 'get' y el parámetro se extrae automáticamente de la ruta URL usando {id}
	ObtenerCatalogoPorID(context.Context, *ObtenerCatalogoPorIDRequest) (*CatalogoResponse, error)
	// Los parámetros de consulta (page_size, solo_activos) se envían como Query Strings (?solo_activos=true)
	ListarCatalogos(context.Context, *ListarCatalogosRequest) (*ListarCatalogosResponse, error)
	ActualizarCatalogo(context.Context, *ActualizarCatalogoRequest) (*CatalogoResponse, error)
	EliminarCatalogo(context.Context, *EliminarCatalogoRequest) (*EliminarCatalogoResponse, error)
	mustEmbedUnimplementedCatalogosServiceServer()
}

// UnimplementedCatalogosServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCatalogosServiceServer struct{}

func (UnimplementedCatalogosServiceServer) CrearCatalogo(context.Context, *CrearCatalogoRequest) (*CatalogoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CrearCatalogo not implemented")
}
func (UnimplementedCatalogosServiceServer) ObtenerCatalogoPorID(context.Context, *ObtenerCatalogoPorIDRequest) (*CatalogoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ObtenerCatalogoPorID not implemented")
}
func (UnimplementedCatalogosServiceServer) ListarCatalogos(context.Context, *ListarCatalogosRequest) (*ListarCatalogosResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListarCatalogos not implemented")
}
func (UnimplementedCatalogosServiceServer) ActualizarCatalogo(context.Context, *ActualizarCatalogoRequest) (*CatalogoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ActualizarCatalogo not implemented")
}
func (UnimplementedCatalogosServiceServer) EliminarCatalogo(context.Context, *EliminarCatalogoRequest) (*EliminarCatalogoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EliminarCatalogo not implemented")
}
func (UnimplementedCatalogosServiceServer) mustEmbedUnimplementedCatalogosServiceServer() {}
func (UnimplementedCatalogosServiceServer) testEmbeddedByValue()                          {}

// UnsafeCatalogosServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CatalogosServiceServer will
// result in compilation errors.
type UnsafeCatalogosServiceServer interface {
	mustEmbedUnimplementedCatalogosServiceServer()
}

func RegisterCatalogosServiceServer(s grpc.ServiceRegistrar, srv CatalogosServiceServer) {
	// If the following call panics, it indicates UnimplementedCatalogosServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CatalogosService_ServiceDesc, srv)
}

func _CatalogosService_CrearCatalogo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CrearCatalogoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogosServiceServer).CrearCatalogo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogosService_CrearCatalogo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogosServiceServer).CrearCatalogo(ctx, req.(*CrearCatalogoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogosService_ObtenerCatalogoPorID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ObtenerCatalogoPorIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogosServiceServer).ObtenerCatalogoPorID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogosService_ObtenerCatalogoPorID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogosServiceServer).ObtenerCatalogoPorID(ctx, req.(*ObtenerCatalogoPorIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogosService_ListarCatalogos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListarCatalogosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogosServiceServer).ListarCatalogos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogosService_ListarCatalogos_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogosServiceServer).ListarCatalogos(ctx, req.(*ListarCatalogosRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogosService_ActualizarCatalogo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActualizarCatalogoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogosServiceServer).ActualizarCatalogo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogosService_ActualizarCatalogo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogosServiceServer).ActualizarCatalogo(ctx, req.(*ActualizarCatalogoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogosService_EliminarCatalogo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EliminarCatalogoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogosServiceServer).EliminarCatalogo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogosService_EliminarCatalogo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogosServiceServer).EliminarCatalogo(ctx, req.(*EliminarCatalogoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CatalogosService_ServiceDesc is the grpc.ServiceDesc for CatalogosService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CatalogosService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dbgs.v1.CatalogosService",
	HandlerType: (*CatalogosServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CrearCatalogo",
			Handler:    _CatalogosService_CrearCatalogo_Handler,
		},
		{
			MethodName: "ObtenerCatalogoPorID",
			Handler:    _CatalogosService_ObtenerCatalogoPorID_Handler,
		},
		{
			MethodName: "ListarCatalogos",
			Handler:    _CatalogosService_ListarCatalogos_Handler,
		},
		{
			MethodName: "ActualizarCatalogo",
			Handler:    _CatalogosService_ActualizarCatalogo_Handler,
		},
		{
			MethodName: "EliminarCatalogo",
			Handler:    _CatalogosService_EliminarCatalogo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "catalogos_servicio.proto",
}
