// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: colecciones_servicio.proto

package dbgsv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CampoDinamicoProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nombre        string                 `protobuf:"bytes,1,opt,name=nombre,proto3" json:"nombre,omitempty"`
	Tipo          string                 `protobuf:"bytes,2,opt,name=tipo,proto3" json:"tipo,omitempty"` // STRING, TEXT, INTEGER, FLOAT, BOOLEAN, UUID, JSONB, TIMESTAMPTZ
	Nulo          bool                   `protobuf:"varint,3,opt,name=nulo,proto3" json:"nulo,omitempty"`
	Unico         bool                   `protobuf:"varint,4,opt,name=unico,proto3" json:"unico,omitempty"`
	Descripcion   string                 `protobuf:"bytes,5,opt,name=descripcion,proto3" json:"descripcion,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CampoDinamicoProto) Reset() {
	*x = CampoDinamicoProto{}
	mi := &file_colecciones_servicio_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CampoDinamicoProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CampoDinamicoProto) ProtoMessage() {}

func (x *CampoDinamicoProto) ProtoReflect() protoreflect.Message {
	mi := &file_colecciones_servicio_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CampoDinamicoProto.ProtoReflect.Descriptor instead.
func (*CampoDinamicoProto) Descriptor() ([]byte, []int) {
	return file_colecciones_servicio_proto_rawDescGZIP(), []int{0}
}

func (x *CampoDinamicoProto) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

func (x *CampoDinamicoProto) GetTipo() string {
	if x != nil {
		return x.Tipo
	}
	return ""
}

func (x *CampoDinamicoProto) GetNulo() bool {
	if x != nil {
		return x.Nulo
	}
	return false
}

func (x *CampoDinamicoProto) GetUnico() bool {
	if x != nil {
		return x.Unico
	}
	return false
}

func (x *CampoDinamicoProto) GetDescripcion() string {
	if x != nil {
		return x.Descripcion
	}
	return ""
}

type CrearColeccionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nombre        string                 `protobuf:"bytes,1,opt,name=nombre,proto3" json:"nombre,omitempty"`
	Descripcion   string                 `protobuf:"bytes,2,opt,name=descripcion,proto3" json:"descripcion,omitempty"`
	Campos        []*CampoDinamicoProto  `protobuf:"bytes,3,rep,name=campos,proto3" json:"campos,omitempty"`
	InstitucionId string                 `protobuf:"bytes,4,opt,name=institucion_id,json=institucionId,proto3" json:"institucion_id,omitempty"` // Opcional para futuro RLS
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CrearColeccionRequest) Reset() {
	*x = CrearColeccionRequest{}
	mi := &file_colecciones_servicio_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrearColeccionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrearColeccionRequest) ProtoMessage() {}

func (x *CrearColeccionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_colecciones_servicio_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrearColeccionRequest.ProtoReflect.Descriptor instead.
func (*CrearColeccionRequest) Descriptor() ([]byte, []int) {
	return file_colecciones_servicio_proto_rawDescGZIP(), []int{1}
}

func (x *CrearColeccionRequest) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

func (x *CrearColeccionRequest) GetDescripcion() string {
	if x != nil {
		return x.Descripcion
	}
	return ""
}

func (x *CrearColeccionRequest) GetCampos() []*CampoDinamicoProto {
	if x != nil {
		return x.Campos
	}
	return nil
}

func (x *CrearColeccionRequest) GetInstitucionId() string {
	if x != nil {
		return x.InstitucionId
	}
	return ""
}

type CrearColeccionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	NombreLogico  string                 `protobuf:"bytes,2,opt,name=nombre_logico,json=nombreLogico,proto3" json:"nombre_logico,omitempty"`
	NombreFisico  string                 `protobuf:"bytes,3,opt,name=nombre_fisico,json=nombreFisico,proto3" json:"nombre_fisico,omitempty"` // El prefijo "dyn_" aplicado
	Mensaje       string                 `protobuf:"bytes,4,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CrearColeccionResponse) Reset() {
	*x = CrearColeccionResponse{}
	mi := &file_colecciones_servicio_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrearColeccionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrearColeccionResponse) ProtoMessage() {}

func (x *CrearColeccionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_colecciones_servicio_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrearColeccionResponse.ProtoReflect.Descriptor instead.
func (*CrearColeccionResponse) Descriptor() ([]byte, []int) {
	return file_colecciones_servicio_proto_rawDescGZIP(), []int{2}
}

func (x *CrearColeccionResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CrearColeccionResponse) GetNombreLogico() string {
	if x != nil {
		return x.NombreLogico
	}
	return ""
}

func (x *CrearColeccionResponse) GetNombreFisico() string {
	if x != nil {
		return x.NombreFisico
	}
	return ""
}

func (x *CrearColeccionResponse) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

type ListarColeccionesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListarColeccionesRequest) Reset() {
	*x = ListarColeccionesRequest{}
	mi := &file_colecciones_servicio_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListarColeccionesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListarColeccionesRequest) ProtoMessage() {}

func (x *ListarColeccionesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_colecciones_servicio_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListarColeccionesRequest.ProtoReflect.Descriptor instead.
func (*ListarColeccionesRequest) Descriptor() ([]byte, []int) {
	return file_colecciones_servicio_proto_rawDescGZIP(), []int{3}
}

func (x *ListarColeccionesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListarColeccionesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ColeccionRegistroProto struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	NombreLogico   string                 `protobuf:"bytes,2,opt,name=nombre_logico,json=nombreLogico,proto3" json:"nombre_logico,omitempty"`
	NombreFisico   string                 `protobuf:"bytes,3,opt,name=nombre_fisico,json=nombreFisico,proto3" json:"nombre_fisico,omitempty"`
	Descripcion    string                 `protobuf:"bytes,4,opt,name=descripcion,proto3" json:"descripcion,omitempty"`
	EstructuraJson string                 `protobuf:"bytes,5,opt,name=estructura_json,json=estructuraJson,proto3" json:"estructura_json,omitempty"` // Devuelve el JSON de los campos para que la UI sepa cómo renderizar formularios
	EstaActiva     bool                   `protobuf:"varint,6,opt,name=esta_activa,json=estaActiva,proto3" json:"esta_activa,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ColeccionRegistroProto) Reset() {
	*x = ColeccionRegistroProto{}
	mi := &file_colecciones_servicio_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ColeccionRegistroProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColeccionRegistroProto) ProtoMessage() {}

func (x *ColeccionRegistroProto) ProtoReflect() protoreflect.Message {
	mi := &file_colecciones_servicio_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColeccionRegistroProto.ProtoReflect.Descriptor instead.
func (*ColeccionRegistroProto) Descriptor() ([]byte, []int) {
	return file_colecciones_servicio_proto_rawDescGZIP(), []int{4}
}

func (x *ColeccionRegistroProto) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ColeccionRegistroProto) GetNombreLogico() string {
	if x != nil {
		return x.NombreLogico
	}
	return ""
}

func (x *ColeccionRegistroProto) GetNombreFisico() string {
	if x != nil {
		return x.NombreFisico
	}
	return ""
}

func (x *ColeccionRegistroProto) GetDescripcion() string {
	if x != nil {
		return x.Descripcion
	}
	return ""
}

func (x *ColeccionRegistroProto) GetEstructuraJson() string {
	if x != nil {
		return x.EstructuraJson
	}
	return ""
}

func (x *ColeccionRegistroProto) GetEstaActiva() bool {
	if x != nil {
		return x.EstaActiva
	}
	return false
}

func (x *ColeccionRegistroProto) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type ListarColeccionesResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Colecciones   []*ColeccionRegistroProto `protobuf:"bytes,1,rep,name=colecciones,proto3" json:"colecciones,omitempty"`
	Total         int32                     `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListarColeccionesResponse) Reset() {
	*x = ListarColeccionesResponse{}
	mi := &file_colecciones_servicio_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListarColeccionesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListarColeccionesResponse) ProtoMessage() {}

func (x *ListarColeccionesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_colecciones_servicio_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListarColeccionesResponse.ProtoReflect.Descriptor instead.
func (*ListarColeccionesResponse) Descriptor() ([]byte, []int) {
	return file_colecciones_servicio_proto_rawDescGZIP(), []int{5}
}

func (x *ListarColeccionesResponse) GetColecciones() []*ColeccionRegistroProto {
	if x != nil {
		return x.Colecciones
	}
	return nil
}

func (x *ListarColeccionesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type RenombrarColumnaProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NombreActual  string                 `protobuf:"bytes,1,opt,name=nombre_actual,json=nombreActual,proto3" json:"nombre_actual,omitempty"`
	NombreNuevo   string                 `protobuf:"bytes,2,opt,name=nombre_nuevo,json=nombreNuevo,proto3" json:"nombre_nuevo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenombrarColumnaProto) Reset() {
	*x = RenombrarColumnaProto{}
	mi := &file_colecciones_servicio_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenombrarColumnaProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenombrarColumnaProto) ProtoMessage() {}

func (x *RenombrarColumnaProto) ProtoReflect() protoreflect.Message {
	mi := &file_colecciones_servicio_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenombrarColumnaProto.ProtoReflect.Descriptor instead.
func (*RenombrarColumnaProto) Descriptor() ([]byte, []int) {
	return file_colecciones_servicio_proto_rawDescGZIP(), []int{6}
}

func (x *RenombrarColumnaProto) GetNombreActual() string {
	if x != nil {
		return x.NombreActual
	}
	return ""
}

func (x *RenombrarColumnaProto) GetNombreNuevo() string {
	if x != nil {
		return x.NombreNuevo
	}
	return ""
}

type CambiarTipoColumnaProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nombre        string                 `protobuf:"bytes,1,opt,name=nombre,proto3" json:"nombre,omitempty"`
	NuevoTipo     string                 `protobuf:"bytes,2,opt,name=nuevo_tipo,json=nuevoTipo,proto3" json:"nuevo_tipo,omitempty"` // STRING, TEXT, INTEGER, FLOAT, BOOLEAN, UUID, JSONB, TIMESTAMPTZ
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CambiarTipoColumnaProto) Reset() {
	*x = CambiarTipoColumnaProto{}
	mi := &file_colecciones_servicio_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CambiarTipoColumnaProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CambiarTipoColumnaProto) ProtoMessage() {}

func (x *CambiarTipoColumnaProto) ProtoReflect() protoreflect.Message {
	mi := &file_colecciones_servicio_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CambiarTipoColumnaProto.ProtoReflect.Descriptor instead.
func (*CambiarTipoColumnaProto) Descriptor() ([]byte, []int) {
	return file_colecciones_servicio_proto_rawDescGZIP(), []int{7}
}

func (x *CambiarTipoColumnaProto) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

func (x *CambiarTipoColumnaProto) GetNuevoTipo() string {
	if x != nil {
		return x.NuevoTipo
	}
	return ""
}

type ActualizarColeccionRequest struct {
	state           protoimpl.MessageState     `protogen:"open.v1"`
	Nombre          string                     `protobuf:"bytes,1,opt,name=nombre,proto3" json:"nombre,omitempty"`                                          // Nombre actual (del URL)
	NuevoNombre     string                     `protobuf:"bytes,2,opt,name=nuevo_nombre,json=nuevoNombre,proto3" json:"nuevo_nombre,omitempty"`             // Renombrar tabla (requiere confirmar)
	Descripcion     string                     `protobuf:"bytes,3,opt,name=descripcion,proto3" json:"descripcion,omitempty"`                                // Actualizar descripción (vacío = sin cambio)
	CamposAgregar   []*CampoDinamicoProto      `protobuf:"bytes,4,rep,name=campos_agregar,json=camposAgregar,proto3" json:"campos_agregar,omitempty"`       // Columnas nuevas a agregar
	CamposRenombrar []*RenombrarColumnaProto   `protobuf:"bytes,5,rep,name=campos_renombrar,json=camposRenombrar,proto3" json:"campos_renombrar,omitempty"` // Columnas a renombrar
	CamposTipo      []*CambiarTipoColumnaProto `protobuf:"bytes,6,rep,name=campos_tipo,json=camposTipo,proto3" json:"campos_tipo,omitempty"`                // Columnas a cambiar tipo
	CamposEliminar  []string                   `protobuf:"bytes,7,rep,name=campos_eliminar,json=camposEliminar,proto3" json:"campos_eliminar,omitempty"`    // Nombres de columnas a eliminar
	Confirmar       bool                       `protobuf:"varint,8,opt,name=confirmar,proto3" json:"confirmar,omitempty"`                                   // Requerido para drops y rename de tabla
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ActualizarColeccionRequest) Reset() {
	*x = ActualizarColeccionRequest{}
	mi := &file_colecciones_servicio_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActualizarColeccionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActualizarColeccionRequest) ProtoMessage() {}

func (x *ActualizarColeccionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_colecciones_servicio_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActualizarColeccionRequest.ProtoReflect.Descriptor instead.
func (*ActualizarColeccionRequest) Descriptor() ([]byte, []int) {
	return file_colecciones_servicio_proto_rawDescGZIP(), []int{8}
}

func (x *ActualizarColeccionRequest) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

func (x *ActualizarColeccionRequest) GetNuevoNombre() string {
	if x != nil {
		return x.NuevoNombre
	}
	return ""
}

func (x *ActualizarColeccionRequest) GetDescripcion() string {
	if x != nil {
		return x.Descripcion
	}
	return ""
}

func (x *ActualizarColeccionRequest) GetCamposAgregar() []*CampoDinamicoProto {
	if x != nil {
		return x.CamposAgregar
	}
	return nil
}

func (x *ActualizarColeccionRequest) GetCamposRenombrar() []*RenombrarColumnaProto {
	if x != nil {
		return x.CamposRenombrar
	}
	return nil
}

func (x *ActualizarColeccionRequest) GetCamposTipo() []*CambiarTipoColumnaProto {
	if x != nil {
		return x.CamposTipo
	}
	return nil
}

func (x *ActualizarColeccionRequest) GetCamposEliminar() []string {
	if x != nil {
		return x.CamposEliminar
	}
	return nil
}

func (x *ActualizarColeccionRequest) GetConfirmar() bool {
	if x != nil {
		return x.Confirmar
	}
	return false
}

type ActualizarColeccionResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	NombreLogico        string                 `protobuf:"bytes,2,opt,name=nombre_logico,json=nombreLogico,proto3" json:"nombre_logico,omitempty"`
	CamposAgregados     int32                  `protobuf:"varint,3,opt,name=campos_agregados,json=camposAgregados,proto3" json:"campos_agregados,omitempty"`
	CamposRenombrados   int32                  `protobuf:"varint,4,opt,name=campos_renombrados,json=camposRenombrados,proto3" json:"campos_renombrados,omitempty"`
	CamposTipoCambiado  int32                  `protobuf:"varint,5,opt,name=campos_tipo_cambiado,json=camposTipoCambiado,proto3" json:"campos_tipo_cambiado,omitempty"`
	CamposEliminar      int32                  `protobuf:"varint,6,opt,name=campos_eliminar,json=camposEliminar,proto3" json:"campos_eliminar,omitempty"`
	NombreTablaAnterior string                 `protobuf:"bytes,7,opt,name=nombre_tabla_anterior,json=nombreTablaAnterior,proto3" json:"nombre_tabla_anterior,omitempty"` // Solo se llena si se renombró la tabla
	Mensaje             string                 `protobuf:"bytes,8,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ActualizarColeccionResponse) Reset() {
	*x = ActualizarColeccionResponse{}
	mi := &file_colecciones_servicio_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActualizarColeccionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActualizarColeccionResponse) ProtoMessage() {}

func (x *ActualizarColeccionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_colecciones_servicio_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActualizarColeccionResponse.ProtoReflect.Descriptor instead.
func (*ActualizarColeccionResponse) Descriptor() ([]byte, []int) {
	return file_colecciones_servicio_proto_rawDescGZIP(), []int{9}
}

func (x *ActualizarColeccionResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ActualizarColeccionResponse) GetNombreLogico() string {
	if x != nil {
		return x.NombreLogico
	}
	return ""
}

func (x *ActualizarColeccionResponse) GetCamposAgregados() int32 {
	if x != nil {
		return x.CamposAgregados
	}
	return 0
}

func (x *ActualizarColeccionResponse) GetCamposRenombrados() int32 {
	if x != nil {
		return x.CamposRenombrados
	}
	return 0
}

func (x *ActualizarColeccionResponse) GetCamposTipoCambiado() int32 {
	if x != nil {
		return x.CamposTipoCambiado
	}
	return 0
}

func (x *ActualizarColeccionResponse) GetCamposEliminar() int32 {
	if x != nil {
		return x.CamposEliminar
	}
	return 0
}

func (x *ActualizarColeccionResponse) GetNombreTablaAnterior() string {
	if x != nil {
		return x.NombreTablaAnterior
	}
	return ""
}

func (x *ActualizarColeccionResponse) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

type EliminarColeccionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nombre        string                 `protobuf:"bytes,1,opt,name=nombre,proto3" json:"nombre,omitempty"`        // Nombre lógico de la colección a eliminar
	Confirmar     bool                   `protobuf:"varint,2,opt,name=confirmar,proto3" json:"confirmar,omitempty"` // true = DROP TABLE + DELETE metadata; false = soft delete (esta_activa=false)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EliminarColeccionRequest) Reset() {
	*x = EliminarColeccionRequest{}
	mi := &file_colecciones_servicio_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EliminarColeccionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EliminarColeccionRequest) ProtoMessage() {}

func (x *EliminarColeccionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_colecciones_servicio_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EliminarColeccionRequest.ProtoReflect.Descriptor instead.
func (*EliminarColeccionRequest) Descriptor() ([]byte, []int) {
	return file_colecciones_servicio_proto_rawDescGZIP(), []int{10}
}

func (x *EliminarColeccionRequest) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

func (x *EliminarColeccionRequest) GetConfirmar() bool {
	if x != nil {
		return x.Confirmar
	}
	return false
}

type EliminarColeccionResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NombreLogico    string                 `protobuf:"bytes,1,opt,name=nombre_logico,json=nombreLogico,proto3" json:"nombre_logico,omitempty"`
	AccionRealizada string                 `protobuf:"bytes,2,opt,name=accion_realizada,json=accionRealizada,proto3" json:"accion_realizada,omitempty"` // "desactivada" o "eliminada"
	Mensaje         string                 `protobuf:"bytes,3,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EliminarColeccionResponse) Reset() {
	*x = EliminarColeccionResponse{}
	mi := &file_colecciones_servicio_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EliminarColeccionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EliminarColeccionResponse) ProtoMessage() {}

func (x *EliminarColeccionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_colecciones_servicio_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EliminarColeccionResponse.ProtoReflect.Descriptor instead.
func (*EliminarColeccionResponse) Descriptor() ([]byte, []int) {
	return file_colecciones_servicio_proto_rawDescGZIP(), []int{11}
}

func (x *EliminarColeccionResponse) GetNombreLogico() string {
	if x != nil {
		return x.NombreLogico
	}
	return ""
}

func (x *EliminarColeccionResponse) GetAccionRealizada() string {
	if x != nil {
		return x.AccionRealizada
	}
	return ""
}

func (x *EliminarColeccionResponse) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

var File_colecciones_servicio_proto protoreflect.FileDescriptor

const file_colecciones_servicio_proto_rawDesc = "" +
	"\n" +
	"\x1acolecciones_servicio.proto\x12\adbgs.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8c\x01\n" +
	"\x12CampoDinamicoProto\x12\x16\n" +
	"\x06nombre\x18\x01 \x01(\tR\x06nombre\x12\x12\n" +
	"\x04tipo\x18\x02 \x01(\tR\x04tipo\x12\x12\n" +
	"\x04nulo\x18\x03 \x01(\bR\x04nulo\x12\x14\n" +
	"\x05unico\x18\x04 \x01(\bR\x05unico\x12 \n" +
	"\vdescripcion\x18\x05 \x01(\tR\vdescripcion\"\xad\x01\n" +
	"\x15CrearColeccionRequest\x12\x16\n" +
	"\x06nombre\x18\x01 \x01(\tR\x06nombre\x12 \n" +
	"\vdescripcion\x18\x02 \x01(\tR\vdescripcion\x123\n" +
	"\x06campos\x18\x03 \x03(\v2\x1b.dbgs.v1.CampoDinamicoProtoR\x06campos\x12%\n" +
	"\x0einstitucion_id\x18\x04 \x01(\tR\rinstitucionId\"\x8c\x01\n" +
	"\x16CrearColeccionResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rnombre_logico\x18\x02 \x01(\tR\fnombreLogico\x12#\n" +
	"\rnombre_fisico\x18\x03 \x01(\tR\fnombreFisico\x12\x18\n" +
	"\amensaje\x18\x04 \x01(\tR\amensaje\"H\n" +
	"\x18ListarColeccionesRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"\xfd\x01\n" +
	"\x16ColeccionRegistroProto\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rnombre_logico\x18\x02 \x01(\tR\fnombreLogico\x12#\n" +
	"\rnombre_fisico\x18\x03 \x01(\tR\fnombreFisico\x12 \n" +
	"\vdescripcion\x18\x04 \x01(\tR\vdescripcion\x12'\n" +
	"\x0festructura_json\x18\x05 \x01(\tR\x0eestructuraJson\x12\x1f\n" +
	"\vesta_activa\x18\x06 \x01(\bR\n" +
	"estaActiva\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\"t\n" +
	"\x19ListarColeccionesResponse\x12A\n" +
	"\vcolecciones\x18\x01 \x03(\v2\x1f.dbgs.v1.ColeccionRegistroProtoR\vcolecciones\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"_\n" +
	"\x15RenombrarColumnaProto\x12#\n" +
	"\rnombre_actual\x18\x01 \x01(\tR\fnombreActual\x12!\n" +
	"\fnombre_nuevo\x18\x02 \x01(\tR\vnombreNuevo\"P\n" +
	"\x17CambiarTipoColumnaProto\x12\x16\n" +
	"\x06nombre\x18\x01 \x01(\tR\x06nombre\x12\x1d\n" +
	"\n" +
	"nuevo_tipo\x18\x02 \x01(\tR\tnuevoTipo\"\x92\x03\n" +
	"\x1aActualizarColeccionRequest\x12\x16\n" +
	"\x06nombre\x18\x01 \x01(\tR\x06nombre\x12!\n" +
	"\fnuevo_nombre\x18\x02 \x01(\tR\vnuevoNombre\x12 \n" +
	"\vdescripcion\x18\x03 \x01(\tR\vdescripcion\x12B\n" +
	"\x0ecampos_agregar\x18\x04 \x03(\v2\x1b.dbgs.v1.CampoDinamicoProtoR\rcamposAgregar\x12I\n" +
	"\x10campos_renombrar\x18\x05 \x03(\v2\x1e.dbgs.v1.RenombrarColumnaProtoR\x0fcamposRenombrar\x12A\n" +
	"\vcampos_tipo\x18\x06 \x03(\v2 .dbgs.v1.CambiarTipoColumnaProtoR\n" +
	"camposTipo\x12'\n" +
	"\x0fcampos_eliminar\x18\a \x03(\tR\x0ecamposEliminar\x12\x1c\n" +
	"\tconfirmar\x18\b \x01(\bR\tconfirmar\"\xd5\x02\n" +
	"\x1bActualizarColeccionResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rnombre_logico\x18\x02 \x01(\tR\fnombreLogico\x12)\n" +
	"\x10campos_agregados\x18\x03 \x01(\x05R\x0fcamposAgregados\x12-\n" +
	"\x12campos_renombrados\x18\x04 \x01(\x05R\x11camposRenombrados\x120\n" +
	"\x14campos_tipo_cambiado\x18\x05 \x01(\x05R\x12camposTipoCambiado\x12'\n" +
	"\x0fcampos_eliminar\x18\x06 \x01(\x05R\x0ecamposEliminar\x122\n" +
	"\x15nombre_tabla_anterior\x18\a \x01(\tR\x13nombreTablaAnterior\x12\x18\n" +
	"\amensaje\x18\b \x01(\tR\amensaje\"P\n" +
	"\x18EliminarColeccionRequest\x12\x16\n" +
	"\x06nombre\x18\x01 \x01(\tR\x06nombre\x12\x1c\n" +
	"\tconfirmar\x18\x02 \x01(\bR\tconfirmar\"\x85\x01\n" +
	"\x19EliminarColeccionResponse\x12#\n" +
	"\rnombre_logico\x18\x01 \x01(\tR\fnombreLogico\x12)\n" +
	"\x10accion_realizada\x18\x02 \x01(\tR\x0faccionRealizada\x12\x18\n" +
	"\amensaje\x18\x03 \x01(\tR\amensaje2\x89\x04\n" +
	"\x12ColeccionesService\x12m\n" +
	"\x0eCrearColeccion\x12\x1e.dbgs.v1.CrearColeccionRequest\x1a\x1f.dbgs.v1.CrearColeccionResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/colecciones\x12s\n" +
	"\x11ListarColecciones\x12!.dbgs.v1.ListarColeccionesRequest\x1a\".dbgs.v1.ListarColeccionesResponse\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/v1/colecciones\x12\x90\x01\n" +
	"\x13ActualizarColeccion\x12#.dbgs.v1.ActualizarColeccionRequest\x1a$.dbgs.v1.ActualizarColeccionResponse\".\x82\xd3\xe4\x93\x02(:\x01*\"#/v1/colecciones/{nombre}/actualizar\x12|\n" +
	"\x11EliminarColeccion\x12!.dbgs.v1.EliminarColeccionRequest\x1a\".dbgs.v1.EliminarColeccionResponse\" \x82\xd3\xe4\x93\x02\x1a*\x18/v1/colecciones/{nombre}B+Z)DBGS_SOBERANO_BACKEND/api/proto/v1;dbgsv1b\x06proto3"

var (
	file_colecciones_servicio_proto_rawDescOnce sync.Once
	file_colecciones_servicio_proto_rawDescData []byte
)

func file_colecciones_servicio_proto_rawDescGZIP() []byte {
	file_colecciones_servicio_proto_rawDescOnce.Do(func() {
		file_colecciones_servicio_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_colecciones_servicio_proto_rawDesc), len(file_colecciones_servicio_proto_rawDesc)))
	})
	return file_colecciones_servicio_proto_rawDescData
}

var file_colecciones_servicio_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_colecciones_servicio_proto_goTypes = []any{
	(*CampoDinamicoProto)(nil),          // 0: dbgs.v1.CampoDinamicoProto
	(*CrearColeccionRequest)(nil),       // 1: dbgs.v1.CrearColeccionRequest
	(*CrearColeccionResponse)(nil),      // 2: dbgs.v1.CrearColeccionResponse
	(*ListarColeccionesRequest)(nil),    // 3: dbgs.v1.ListarColeccionesRequest
	(*ColeccionRegistroProto)(nil),      // 4: dbgs.v1.ColeccionRegistroProto
	(*ListarColeccionesResponse)(nil),   // 5: dbgs.v1.ListarColeccionesResponse
	(*RenombrarColumnaProto)(nil),       // 6: dbgs.v1.RenombrarColumnaProto
	(*CambiarTipoColumnaProto)(nil),     // 7: dbgs.v1.CambiarTipoColumnaProto
	(*ActualizarColeccionRequest)(nil),  // 8: dbgs.v1.ActualizarColeccionRequest
	(*ActualizarColeccionResponse)(nil), // 9: dbgs.v1.ActualizarColeccionResponse
	(*EliminarColeccionRequest)(nil),    // 10: dbgs.v1.EliminarColeccionRequest
	(*EliminarColeccionResponse)(nil),   // 11: dbgs.v1.EliminarColeccionResponse
}
var file_colecciones_servicio_proto_depIdxs = []int32{
	0,  // 0: dbgs.v1.CrearColeccionRequest.campos:type_name -> dbgs.v1.CampoDinamicoProto
	4,  // 1: dbgs.v1.ListarColeccionesResponse.colecciones:type_name -> dbgs.v1.ColeccionRegistroProto
	0,  // 2: dbgs.v1.ActualizarColeccionRequest.campos_agregar:type_name -> dbgs.v1.CampoDinamicoProto
	6,  // 3: dbgs.v1.ActualizarColeccionRequest.campos_renombrar:type_name -> dbgs.v1.RenombrarColumnaProto
	7,  // 4: dbgs.v1.ActualizarColeccionRequest.campos_tipo:type_name -> dbgs.v1.CambiarTipoColumnaProto
	1,  // 5: dbgs.v1.ColeccionesService.CrearColeccion:input_type -> dbgs.v1.CrearColeccionRequest
	3,  // 6: dbgs.v1.ColeccionesService.ListarColecciones:input_type -> dbgs.v1.ListarColeccionesRequest
	8,  // 7: dbgs.v1.ColeccionesService.ActualizarColeccion:input_type -> dbgs.v1.ActualizarColeccionRequest
	10, // 8: dbgs.v1.ColeccionesService.EliminarColeccion:input_type -> dbgs.v1.EliminarColeccionRequest
	2,  // 9: dbgs.v1.ColeccionesService.CrearColeccion:output_type -> dbgs.v1.CrearColeccionResponse
	5,  // 10: dbgs.v1.ColeccionesService.ListarColecciones:output_type -> dbgs.v1.ListarColeccionesResponse
	9,  // 11: dbgs.v1.ColeccionesService.ActualizarColeccion:output_type -> dbgs.v1.ActualizarColeccionResponse
	11, // 12: dbgs.v1.ColeccionesService.EliminarColeccion:output_type -> dbgs.v1.EliminarColeccionResponse
	9,  // [9:13] is the sub-list for method output_type
	5,  // [5:9] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_colecciones_servicio_proto_init() }
func file_colecciones_servicio_proto_init() {
	if File_colecciones_servicio_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_colecciones_servicio_proto_rawDesc), len(file_colecciones_servicio_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_colecciones_servicio_proto_goTypes,
		DependencyIndexes: file_colecciones_servicio_proto_depIdxs,
		MessageInfos:      file_colecciones_servicio_proto_msgTypes,
	}.Build()
	File_colecciones_servicio_proto = out.File
	file_colecciones_servicio_proto_goTypes = nil
	file_colecciones_servicio_proto_depIdxs = nil
}
