// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: conexiones_servicio.proto

package dbgsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ConexionesService_ProbarConexion_FullMethodName     = "/dbgs.v1.ConexionesService/ProbarConexion"
	ConexionesService_CrearConexion_FullMethodName      = "/dbgs.v1.ConexionesService/CrearConexion"
	ConexionesService_ListarConexiones_FullMethodName   = "/dbgs.v1.ConexionesService/ListarConexiones"
	ConexionesService_ObtenerConexion_FullMethodName    = "/dbgs.v1.ConexionesService/ObtenerConexion"
	ConexionesService_ActualizarConexion_FullMethodName = "/dbgs.v1.ConexionesService/ActualizarConexion"
	ConexionesService_EliminarConexion_FullMethodName   = "/dbgs.v1.ConexionesService/EliminarConexion"
	ConexionesService_ListarEsquemas_FullMethodName     = "/dbgs.v1.ConexionesService/ListarEsquemas"
	ConexionesService_ListarTablas_FullMethodName       = "/dbgs.v1.ConexionesService/ListarTablas"
	ConexionesService_ExplorarDatos_FullMethodName      = "/dbgs.v1.ConexionesService/ExplorarDatos"
)

// ConexionesServiceClient is the client API for ConexionesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Servicio gRPC para la administración de conexiones a bases de datos externas.
// Permite registrar, probar y explorar fuentes de datos conectadas (PostgreSQL/MySQL).
type ConexionesServiceClient interface {
	ProbarConexion(ctx context.Context, in *ProbarConexionRequest, opts ...grpc.CallOption) (*ProbarConexionResponse, error)
	CrearConexion(ctx context.Context, in *CrearConexionRequest, opts ...grpc.CallOption) (*ConexionResponse, error)
	ListarConexiones(ctx context.Context, in *ListarConexionesRequest, opts ...grpc.CallOption) (*ListarConexionesResponse, error)
	ObtenerConexion(ctx context.Context, in *ObtenerConexionRequest, opts ...grpc.CallOption) (*ConexionResponse, error)
	ActualizarConexion(ctx context.Context, in *ActualizarConexionRequest, opts ...grpc.CallOption) (*ConexionResponse, error)
	EliminarConexion(ctx context.Context, in *EliminarConexionRequest, opts ...grpc.CallOption) (*EliminarConexionResponse, error)
	ListarEsquemas(ctx context.Context, in *ListarEsquemasRequest, opts ...grpc.CallOption) (*ListarEsquemasResponse, error)
	ListarTablas(ctx context.Context, in *ListarTablasRequest, opts ...grpc.CallOption) (*ListarTablasResponse, error)
	ExplorarDatos(ctx context.Context, in *ExplorarDatosRequest, opts ...grpc.CallOption) (*ExplorarDatosResponse, error)
}

type conexionesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewConexionesServiceClient(cc grpc.ClientConnInterface) ConexionesServiceClient {
	return &conexionesServiceClient{cc}
}

func (c *conexionesServiceClient) ProbarConexion(ctx context.Context, in *ProbarConexionRequest, opts ...grpc.CallOption) (*ProbarConexionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProbarConexionResponse)
	err := c.cc.Invoke(ctx, ConexionesService_ProbarConexion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conexionesServiceClient) CrearConexion(ctx context.Context, in *CrearConexionRequest, opts ...grpc.CallOption) (*ConexionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConexionResponse)
	err := c.cc.Invoke(ctx, ConexionesService_CrearConexion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conexionesServiceClient) ListarConexiones(ctx context.Context, in *ListarConexionesRequest, opts ...grpc.CallOption) (*ListarConexionesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListarConexionesResponse)
	err := c.cc.Invoke(ctx, ConexionesService_ListarConexiones_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conexionesServiceClient) ObtenerConexion(ctx context.Context, in *ObtenerConexionRequest, opts ...grpc.CallOption) (*ConexionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConexionResponse)
	err := c.cc.Invoke(ctx, ConexionesService_ObtenerConexion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conexionesServiceClient) ActualizarConexion(ctx context.Context, in *ActualizarConexionRequest, opts ...grpc.CallOption) (*ConexionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConexionResponse)
	err := c.cc.Invoke(ctx, ConexionesService_ActualizarConexion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conexionesServiceClient) EliminarConexion(ctx context.Context, in *EliminarConexionRequest, opts ...grpc.CallOption) (*EliminarConexionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EliminarConexionResponse)
	err := c.cc.Invoke(ctx, ConexionesService_EliminarConexion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conexionesServiceClient) ListarEsquemas(ctx context.Context, in *ListarEsquemasRequest, opts ...grpc.CallOption) (*ListarEsquemasResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListarEsquemasResponse)
	err := c.cc.Invoke(ctx, ConexionesService_ListarEsquemas_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conexionesServiceClient) ListarTablas(ctx context.Context, in *ListarTablasRequest, opts ...grpc.CallOption) (*ListarTablasResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListarTablasResponse)
	err := c.cc.Invoke(ctx, ConexionesService_ListarTablas_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conexionesServiceClient) ExplorarDatos(ctx context.Context, in *ExplorarDatosRequest, opts ...grpc.CallOption) (*ExplorarDatosResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExplorarDatosResponse)
	err := c.cc.Invoke(ctx, ConexionesService_ExplorarDatos_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConexionesServiceServer is the server API for ConexionesService service.
// All implementations must embed UnimplementedConexionesServiceServer
// for forward compatibility.
//
// Servicio gRPC para la administración de conexiones a bases de datos externas.
// Permite registrar, probar y explorar fuentes de datos conectadas (PostgreSQL/MySQL).
type ConexionesServiceServer interface {
	ProbarConexion(context.Context, *ProbarConexionRequest) (*ProbarConexionResponse, error)
	CrearConexion(context.Context, *CrearConexionRequest) (*ConexionResponse, error)
	ListarConexiones(context.Context, *ListarConexionesRequest) (*ListarConexionesResponse, error)
	ObtenerConexion(context.Context, *ObtenerConexionRequest) (*ConexionResponse, error)
	ActualizarConexion(context.Context, *ActualizarConexionRequest) (*ConexionResponse, error)
	EliminarConexion(context.Context, *EliminarConexionRequest) (*EliminarConexionResponse, error)
	ListarEsquemas(context.Context, *ListarEsquemasRequest) (*ListarEsquemasResponse, error)
	ListarTablas(context.Context, *ListarTablasRequest) (*ListarTablasResponse, error)
	ExplorarDatos(context.Context, *ExplorarDatosRequest) (*ExplorarDatosResponse, error)
	mustEmbedUnimplementedConexionesServiceServer()
}

// UnimplementedConexionesServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConexionesServiceServer struct{}

func (UnimplementedConexionesServiceServer) ProbarConexion(context.Context, *ProbarConexionRequest) (*ProbarConexionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProbarConexion not implemented")
}
func (UnimplementedConexionesServiceServer) CrearConexion(context.Context, *CrearConexionRequest) (*ConexionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CrearConexion not implemented")
}
func (UnimplementedConexionesServiceServer) ListarConexiones(context.Context, *ListarConexionesRequest) (*ListarConexionesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListarConexiones not implemented")
}
func (UnimplementedConexionesServiceServer) ObtenerConexion(context.Context, *ObtenerConexionRequest) (*ConexionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ObtenerConexion not implemented")
}
func (UnimplementedConexionesServiceServer) ActualizarConexion(context.Context, *ActualizarConexionRequest) (*ConexionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ActualizarConexion not implemented")
}
func (UnimplementedConexionesServiceServer) EliminarConexion(context.Context, *EliminarConexionRequest) (*EliminarConexionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EliminarConexion not implemented")
}
func (UnimplementedConexionesServiceServer) ListarEsquemas(context.Context, *ListarEsquemasRequest) (*ListarEsquemasResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListarEsquemas not implemented")
}
func (UnimplementedConexionesServiceServer) ListarTablas(context.Context, *ListarTablasRequest) (*ListarTablasResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListarTablas not implemented")
}
func (UnimplementedConexionesServiceServer) ExplorarDatos(context.Context, *ExplorarDatosRequest) (*ExplorarDatosResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExplorarDatos not implemented")
}
func (UnimplementedConexionesServiceServer) mustEmbedUnimplementedConexionesServiceServer() {}
func (UnimplementedConexionesServiceServer) testEmbeddedByValue()                           {}

// UnsafeConexionesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConexionesServiceServer will
// result in compilation errors.
type UnsafeConexionesServiceServer interface {
	mustEmbedUnimplementedConexionesServiceServer()
}

func RegisterConexionesServiceServer(s grpc.ServiceRegistrar, srv ConexionesServiceServer) {
	// If the following call panics, it indicates UnimplementedConexionesServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConexionesService_ServiceDesc, srv)
}

func _ConexionesService_ProbarConexion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProbarConexionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConexionesServiceServer).ProbarConexion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConexionesService_ProbarConexion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConexionesServiceServer).ProbarConexion(ctx, req.(*ProbarConexionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConexionesService_CrearConexion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CrearConexionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConexionesServiceServer).CrearConexion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConexionesService_CrearConexion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConexionesServiceServer).CrearConexion(ctx, req.(*CrearConexionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConexionesService_ListarConexiones_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListarConexionesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConexionesServiceServer).ListarConexiones(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConexionesService_ListarConexiones_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConexionesServiceServer).ListarConexiones(ctx, req.(*ListarConexionesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConexionesService_ObtenerConexion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ObtenerConexionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConexionesServiceServer).ObtenerConexion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConexionesService_ObtenerConexion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConexionesServiceServer).ObtenerConexion(ctx, req.(*ObtenerConexionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConexionesService_ActualizarConexion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActualizarConexionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConexionesServiceServer).ActualizarConexion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConexionesService_ActualizarConexion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConexionesServiceServer).ActualizarConexion(ctx, req.(*ActualizarConexionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConexionesService_EliminarConexion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EliminarConexionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConexionesServiceServer).EliminarConexion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConexionesService_EliminarConexion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConexionesServiceServer).EliminarConexion(ctx, req.(*EliminarConexionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConexionesService_ListarEsquemas_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListarEsquemasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConexionesServiceServer).ListarEsquemas(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConexionesService_ListarEsquemas_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConexionesServiceServer).ListarEsquemas(ctx, req.(*ListarEsquemasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConexionesService_ListarTablas_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListarTablasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConexionesServiceServer).ListarTablas(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConexionesService_ListarTablas_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConexionesServiceServer).ListarTablas(ctx, req.(*ListarTablasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConexionesService_ExplorarDatos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExplorarDatosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConexionesServiceServer).ExplorarDatos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConexionesService_ExplorarDatos_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConexionesServiceServer).ExplorarDatos(ctx, req.(*ExplorarDatosRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ConexionesService_ServiceDesc is the grpc.ServiceDesc for ConexionesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConexionesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dbgs.v1.ConexionesService",
	HandlerType: (*ConexionesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProbarConexion",
			Handler:    _ConexionesService_ProbarConexion_Handler,
		},
		{
			MethodName: "CrearConexion",
			Handler:    _ConexionesService_CrearConexion_Handler,
		},
		{
			MethodName: "ListarConexiones",
			Handler:    _ConexionesService_ListarConexiones_Handler,
		},
		{
			MethodName: "ObtenerConexion",
			Handler:    _ConexionesService_ObtenerConexion_Handler,
		},
		{
			MethodName: "ActualizarConexion",
			Handler:    _ConexionesService_ActualizarConexion_Handler,
		},
		{
			MethodName: "EliminarConexion",
			Handler:    _ConexionesService_EliminarConexion_Handler,
		},
		{
			MethodName: "ListarEsquemas",
			Handler:    _ConexionesService_ListarEsquemas_Handler,
		},
		{
			MethodName: "ListarTablas",
			Handler:    _ConexionesService_ListarTablas_Handler,
		},
		{
			MethodName: "ExplorarDatos",
			Handler:    _ConexionesService_ExplorarDatos_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "conexiones_servicio.proto",
}
