// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: datos_dinamicos_servicio.proto

package dbgsv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListarRegistrosRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NombreTabla   string                 `protobuf:"bytes,1,opt,name=nombre_tabla,json=nombreTabla,proto3" json:"nombre_tabla,omitempty"` // Ej: 'ciudadanos' (El sistema buscará internamente 'dyn_ciudadanos')
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListarRegistrosRequest) Reset() {
	*x = ListarRegistrosRequest{}
	mi := &file_datos_dinamicos_servicio_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListarRegistrosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListarRegistrosRequest) ProtoMessage() {}

func (x *ListarRegistrosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_datos_dinamicos_servicio_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListarRegistrosRequest.ProtoReflect.Descriptor instead.
func (*ListarRegistrosRequest) Descriptor() ([]byte, []int) {
	return file_datos_dinamicos_servicio_proto_rawDescGZIP(), []int{0}
}

func (x *ListarRegistrosRequest) GetNombreTabla() string {
	if x != nil {
		return x.NombreTabla
	}
	return ""
}

func (x *ListarRegistrosRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListarRegistrosRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ObtenerRegistroRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NombreTabla   string                 `protobuf:"bytes,1,opt,name=nombre_tabla,json=nombreTabla,proto3" json:"nombre_tabla,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"` // UUID del registro
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObtenerRegistroRequest) Reset() {
	*x = ObtenerRegistroRequest{}
	mi := &file_datos_dinamicos_servicio_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObtenerRegistroRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObtenerRegistroRequest) ProtoMessage() {}

func (x *ObtenerRegistroRequest) ProtoReflect() protoreflect.Message {
	mi := &file_datos_dinamicos_servicio_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObtenerRegistroRequest.ProtoReflect.Descriptor instead.
func (*ObtenerRegistroRequest) Descriptor() ([]byte, []int) {
	return file_datos_dinamicos_servicio_proto_rawDescGZIP(), []int{1}
}

func (x *ObtenerRegistroRequest) GetNombreTabla() string {
	if x != nil {
		return x.NombreTabla
	}
	return ""
}

func (x *ObtenerRegistroRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CrearRegistroRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NombreTabla   string                 `protobuf:"bytes,1,opt,name=nombre_tabla,json=nombreTabla,proto3" json:"nombre_tabla,omitempty"`
	Datos         *structpb.Struct       `protobuf:"bytes,2,opt,name=datos,proto3" json:"datos,omitempty"` // JSON dinámico con los campos a insertar
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CrearRegistroRequest) Reset() {
	*x = CrearRegistroRequest{}
	mi := &file_datos_dinamicos_servicio_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrearRegistroRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrearRegistroRequest) ProtoMessage() {}

func (x *CrearRegistroRequest) ProtoReflect() protoreflect.Message {
	mi := &file_datos_dinamicos_servicio_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrearRegistroRequest.ProtoReflect.Descriptor instead.
func (*CrearRegistroRequest) Descriptor() ([]byte, []int) {
	return file_datos_dinamicos_servicio_proto_rawDescGZIP(), []int{2}
}

func (x *CrearRegistroRequest) GetNombreTabla() string {
	if x != nil {
		return x.NombreTabla
	}
	return ""
}

func (x *CrearRegistroRequest) GetDatos() *structpb.Struct {
	if x != nil {
		return x.Datos
	}
	return nil
}

type ActualizarRegistroRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NombreTabla   string                 `protobuf:"bytes,1,opt,name=nombre_tabla,json=nombreTabla,proto3" json:"nombre_tabla,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Datos         *structpb.Struct       `protobuf:"bytes,3,opt,name=datos,proto3" json:"datos,omitempty"` // JSON dinámico con solo los campos a modificar
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActualizarRegistroRequest) Reset() {
	*x = ActualizarRegistroRequest{}
	mi := &file_datos_dinamicos_servicio_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActualizarRegistroRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActualizarRegistroRequest) ProtoMessage() {}

func (x *ActualizarRegistroRequest) ProtoReflect() protoreflect.Message {
	mi := &file_datos_dinamicos_servicio_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActualizarRegistroRequest.ProtoReflect.Descriptor instead.
func (*ActualizarRegistroRequest) Descriptor() ([]byte, []int) {
	return file_datos_dinamicos_servicio_proto_rawDescGZIP(), []int{3}
}

func (x *ActualizarRegistroRequest) GetNombreTabla() string {
	if x != nil {
		return x.NombreTabla
	}
	return ""
}

func (x *ActualizarRegistroRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ActualizarRegistroRequest) GetDatos() *structpb.Struct {
	if x != nil {
		return x.Datos
	}
	return nil
}

type EliminarRegistroRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NombreTabla   string                 `protobuf:"bytes,1,opt,name=nombre_tabla,json=nombreTabla,proto3" json:"nombre_tabla,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EliminarRegistroRequest) Reset() {
	*x = EliminarRegistroRequest{}
	mi := &file_datos_dinamicos_servicio_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EliminarRegistroRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EliminarRegistroRequest) ProtoMessage() {}

func (x *EliminarRegistroRequest) ProtoReflect() protoreflect.Message {
	mi := &file_datos_dinamicos_servicio_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EliminarRegistroRequest.ProtoReflect.Descriptor instead.
func (*EliminarRegistroRequest) Descriptor() ([]byte, []int) {
	return file_datos_dinamicos_servicio_proto_rawDescGZIP(), []int{4}
}

func (x *EliminarRegistroRequest) GetNombreTabla() string {
	if x != nil {
		return x.NombreTabla
	}
	return ""
}

func (x *EliminarRegistroRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListarRegistrosResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Registros     []*structpb.Struct     `protobuf:"bytes,1,rep,name=registros,proto3" json:"registros,omitempty"` // Array de objetos JSON dinámicos
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListarRegistrosResponse) Reset() {
	*x = ListarRegistrosResponse{}
	mi := &file_datos_dinamicos_servicio_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListarRegistrosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListarRegistrosResponse) ProtoMessage() {}

func (x *ListarRegistrosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_datos_dinamicos_servicio_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListarRegistrosResponse.ProtoReflect.Descriptor instead.
func (*ListarRegistrosResponse) Descriptor() ([]byte, []int) {
	return file_datos_dinamicos_servicio_proto_rawDescGZIP(), []int{5}
}

func (x *ListarRegistrosResponse) GetRegistros() []*structpb.Struct {
	if x != nil {
		return x.Registros
	}
	return nil
}

func (x *ListarRegistrosResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ObtenerRegistroResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Registro      *structpb.Struct       `protobuf:"bytes,1,opt,name=registro,proto3" json:"registro,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObtenerRegistroResponse) Reset() {
	*x = ObtenerRegistroResponse{}
	mi := &file_datos_dinamicos_servicio_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObtenerRegistroResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObtenerRegistroResponse) ProtoMessage() {}

func (x *ObtenerRegistroResponse) ProtoReflect() protoreflect.Message {
	mi := &file_datos_dinamicos_servicio_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObtenerRegistroResponse.ProtoReflect.Descriptor instead.
func (*ObtenerRegistroResponse) Descriptor() ([]byte, []int) {
	return file_datos_dinamicos_servicio_proto_rawDescGZIP(), []int{6}
}

func (x *ObtenerRegistroResponse) GetRegistro() *structpb.Struct {
	if x != nil {
		return x.Registro
	}
	return nil
}

type CrearRegistroResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // UUID del nuevo registro creado
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CrearRegistroResponse) Reset() {
	*x = CrearRegistroResponse{}
	mi := &file_datos_dinamicos_servicio_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrearRegistroResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrearRegistroResponse) ProtoMessage() {}

func (x *CrearRegistroResponse) ProtoReflect() protoreflect.Message {
	mi := &file_datos_dinamicos_servicio_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrearRegistroResponse.ProtoReflect.Descriptor instead.
func (*CrearRegistroResponse) Descriptor() ([]byte, []int) {
	return file_datos_dinamicos_servicio_proto_rawDescGZIP(), []int{7}
}

func (x *CrearRegistroResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ActualizarRegistroResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Registro      *structpb.Struct       `protobuf:"bytes,1,opt,name=registro,proto3" json:"registro,omitempty"` // Devuelve el registro actualizado
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActualizarRegistroResponse) Reset() {
	*x = ActualizarRegistroResponse{}
	mi := &file_datos_dinamicos_servicio_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActualizarRegistroResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActualizarRegistroResponse) ProtoMessage() {}

func (x *ActualizarRegistroResponse) ProtoReflect() protoreflect.Message {
	mi := &file_datos_dinamicos_servicio_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActualizarRegistroResponse.ProtoReflect.Descriptor instead.
func (*ActualizarRegistroResponse) Descriptor() ([]byte, []int) {
	return file_datos_dinamicos_servicio_proto_rawDescGZIP(), []int{8}
}

func (x *ActualizarRegistroResponse) GetRegistro() *structpb.Struct {
	if x != nil {
		return x.Registro
	}
	return nil
}

type EliminarRegistroResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exitoso       bool                   `protobuf:"varint,1,opt,name=exitoso,proto3" json:"exitoso,omitempty"`
	Mensaje       string                 `protobuf:"bytes,2,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EliminarRegistroResponse) Reset() {
	*x = EliminarRegistroResponse{}
	mi := &file_datos_dinamicos_servicio_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EliminarRegistroResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EliminarRegistroResponse) ProtoMessage() {}

func (x *EliminarRegistroResponse) ProtoReflect() protoreflect.Message {
	mi := &file_datos_dinamicos_servicio_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EliminarRegistroResponse.ProtoReflect.Descriptor instead.
func (*EliminarRegistroResponse) Descriptor() ([]byte, []int) {
	return file_datos_dinamicos_servicio_proto_rawDescGZIP(), []int{9}
}

func (x *EliminarRegistroResponse) GetExitoso() bool {
	if x != nil {
		return x.Exitoso
	}
	return false
}

func (x *EliminarRegistroResponse) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

var File_datos_dinamicos_servicio_proto protoreflect.FileDescriptor

const file_datos_dinamicos_servicio_proto_rawDesc = "" +
	"\n" +
	"\x1edatos_dinamicos_servicio.proto\x12\adbgs.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1cgoogle/protobuf/struct.proto\"i\n" +
	"\x16ListarRegistrosRequest\x12!\n" +
	"\fnombre_tabla\x18\x01 \x01(\tR\vnombreTabla\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"K\n" +
	"\x16ObtenerRegistroRequest\x12!\n" +
	"\fnombre_tabla\x18\x01 \x01(\tR\vnombreTabla\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"h\n" +
	"\x14CrearRegistroRequest\x12!\n" +
	"\fnombre_tabla\x18\x01 \x01(\tR\vnombreTabla\x12-\n" +
	"\x05datos\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x05datos\"}\n" +
	"\x19ActualizarRegistroRequest\x12!\n" +
	"\fnombre_tabla\x18\x01 \x01(\tR\vnombreTabla\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12-\n" +
	"\x05datos\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x05datos\"L\n" +
	"\x17EliminarRegistroRequest\x12!\n" +
	"\fnombre_tabla\x18\x01 \x01(\tR\vnombreTabla\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"f\n" +
	"\x17ListarRegistrosResponse\x125\n" +
	"\tregistros\x18\x01 \x03(\v2\x17.google.protobuf.StructR\tregistros\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"N\n" +
	"\x17ObtenerRegistroResponse\x123\n" +
	"\bregistro\x18\x01 \x01(\v2\x17.google.protobuf.StructR\bregistro\"'\n" +
	"\x15CrearRegistroResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"Q\n" +
	"\x1aActualizarRegistroResponse\x123\n" +
	"\bregistro\x18\x01 \x01(\v2\x17.google.protobuf.StructR\bregistro\"N\n" +
	"\x18EliminarRegistroResponse\x12\x18\n" +
	"\aexitoso\x18\x01 \x01(\bR\aexitoso\x12\x18\n" +
	"\amensaje\x18\x02 \x01(\tR\amensaje2\x8e\x05\n" +
	"\x15DatosDinamicosService\x12u\n" +
	"\x0fListarRegistros\x12\x1f.dbgs.v1.ListarRegistrosRequest\x1a .dbgs.v1.ListarRegistrosResponse\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/v1/data/{nombre_tabla}\x12z\n" +
	"\x0fObtenerRegistro\x12\x1f.dbgs.v1.ObtenerRegistroRequest\x1a .dbgs.v1.ObtenerRegistroResponse\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/v1/data/{nombre_tabla}/{id}\x12v\n" +
	"\rCrearRegistro\x12\x1d.dbgs.v1.CrearRegistroRequest\x1a\x1e.dbgs.v1.CrearRegistroResponse\"&\x82\xd3\xe4\x93\x02 :\x05datos\"\x17/v1/data/{nombre_tabla}\x12\x8a\x01\n" +
	"\x12ActualizarRegistro\x12\".dbgs.v1.ActualizarRegistroRequest\x1a#.dbgs.v1.ActualizarRegistroResponse\"+\x82\xd3\xe4\x93\x02%:\x05datos\x1a\x1c/v1/data/{nombre_tabla}/{id}\x12}\n" +
	"\x10EliminarRegistro\x12 .dbgs.v1.EliminarRegistroRequest\x1a!.dbgs.v1.EliminarRegistroResponse\"$\x82\xd3\xe4\x93\x02\x1e*\x1c/v1/data/{nombre_tabla}/{id}B+Z)DBGS_SOBERANO_BACKEND/api/proto/v1;dbgsv1b\x06proto3"

var (
	file_datos_dinamicos_servicio_proto_rawDescOnce sync.Once
	file_datos_dinamicos_servicio_proto_rawDescData []byte
)

func file_datos_dinamicos_servicio_proto_rawDescGZIP() []byte {
	file_datos_dinamicos_servicio_proto_rawDescOnce.Do(func() {
		file_datos_dinamicos_servicio_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_datos_dinamicos_servicio_proto_rawDesc), len(file_datos_dinamicos_servicio_proto_rawDesc)))
	})
	return file_datos_dinamicos_servicio_proto_rawDescData
}

var file_datos_dinamicos_servicio_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_datos_dinamicos_servicio_proto_goTypes = []any{
	(*ListarRegistrosRequest)(nil),     // 0: dbgs.v1.ListarRegistrosRequest
	(*ObtenerRegistroRequest)(nil),     // 1: dbgs.v1.ObtenerRegistroRequest
	(*CrearRegistroRequest)(nil),       // 2: dbgs.v1.CrearRegistroRequest
	(*ActualizarRegistroRequest)(nil),  // 3: dbgs.v1.ActualizarRegistroRequest
	(*EliminarRegistroRequest)(nil),    // 4: dbgs.v1.EliminarRegistroRequest
	(*ListarRegistrosResponse)(nil),    // 5: dbgs.v1.ListarRegistrosResponse
	(*ObtenerRegistroResponse)(nil),    // 6: dbgs.v1.ObtenerRegistroResponse
	(*CrearRegistroResponse)(nil),      // 7: dbgs.v1.CrearRegistroResponse
	(*ActualizarRegistroResponse)(nil), // 8: dbgs.v1.ActualizarRegistroResponse
	(*EliminarRegistroResponse)(nil),   // 9: dbgs.v1.EliminarRegistroResponse
	(*structpb.Struct)(nil),            // 10: google.protobuf.Struct
}
var file_datos_dinamicos_servicio_proto_depIdxs = []int32{
	10, // 0: dbgs.v1.CrearRegistroRequest.datos:type_name -> google.protobuf.Struct
	10, // 1: dbgs.v1.ActualizarRegistroRequest.datos:type_name -> google.protobuf.Struct
	10, // 2: dbgs.v1.ListarRegistrosResponse.registros:type_name -> google.protobuf.Struct
	10, // 3: dbgs.v1.ObtenerRegistroResponse.registro:type_name -> google.protobuf.Struct
	10, // 4: dbgs.v1.ActualizarRegistroResponse.registro:type_name -> google.protobuf.Struct
	0,  // 5: dbgs.v1.DatosDinamicosService.ListarRegistros:input_type -> dbgs.v1.ListarRegistrosRequest
	1,  // 6: dbgs.v1.DatosDinamicosService.ObtenerRegistro:input_type -> dbgs.v1.ObtenerRegistroRequest
	2,  // 7: dbgs.v1.DatosDinamicosService.CrearRegistro:input_type -> dbgs.v1.CrearRegistroRequest
	3,  // 8: dbgs.v1.DatosDinamicosService.ActualizarRegistro:input_type -> dbgs.v1.ActualizarRegistroRequest
	4,  // 9: dbgs.v1.DatosDinamicosService.EliminarRegistro:input_type -> dbgs.v1.EliminarRegistroRequest
	5,  // 10: dbgs.v1.DatosDinamicosService.ListarRegistros:output_type -> dbgs.v1.ListarRegistrosResponse
	6,  // 11: dbgs.v1.DatosDinamicosService.ObtenerRegistro:output_type -> dbgs.v1.ObtenerRegistroResponse
	7,  // 12: dbgs.v1.DatosDinamicosService.CrearRegistro:output_type -> dbgs.v1.CrearRegistroResponse
	8,  // 13: dbgs.v1.DatosDinamicosService.ActualizarRegistro:output_type -> dbgs.v1.ActualizarRegistroResponse
	9,  // 14: dbgs.v1.DatosDinamicosService.EliminarRegistro:output_type -> dbgs.v1.EliminarRegistroResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_datos_dinamicos_servicio_proto_init() }
func file_datos_dinamicos_servicio_proto_init() {
	if File_datos_dinamicos_servicio_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_datos_dinamicos_servicio_proto_rawDesc), len(file_datos_dinamicos_servicio_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_datos_dinamicos_servicio_proto_goTypes,
		DependencyIndexes: file_datos_dinamicos_servicio_proto_depIdxs,
		MessageInfos:      file_datos_dinamicos_servicio_proto_msgTypes,
	}.Build()
	File_datos_dinamicos_servicio_proto = out.File
	file_datos_dinamicos_servicio_proto_goTypes = nil
	file_datos_dinamicos_servicio_proto_depIdxs = nil
}
