// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: respaldo_servicio.proto

package dbgsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RespaldoService_CrearRespaldo_FullMethodName     = "/dbgs.v1.RespaldoService/CrearRespaldo"
	RespaldoService_ObtenerRespaldo_FullMethodName   = "/dbgs.v1.RespaldoService/ObtenerRespaldo"
	RespaldoService_ListarRespaldos_FullMethodName   = "/dbgs.v1.RespaldoService/ListarRespaldos"
	RespaldoService_DescargarRespaldo_FullMethodName = "/dbgs.v1.RespaldoService/DescargarRespaldo"
	RespaldoService_RestaurarRespaldo_FullMethodName = "/dbgs.v1.RespaldoService/RestaurarRespaldo"
	RespaldoService_AplicarRetencion_FullMethodName  = "/dbgs.v1.RespaldoService/AplicarRetencion"
)

// RespaldoServiceClient is the client API for RespaldoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Servicio de Respaldos y Operación (Dominio 8).
// Orquesta pg_dump/pg_restore mediante los scripts oficiales en db/backup,
// registra cada operación en la bitácora y expone la política de retención.
//
// NOTA DE SEGURIDAD: Todos los métodos requieren autenticación (JWT o API Key).
// La creación/descarga exige el permiso 'respaldo:ejecutar' y la restauración
// exige 'restauracion:ejecutar' (ver db/seeds/seed_users.sql).
type RespaldoServiceClient interface {
	// Lanza un respaldo completo asíncrono (pg_dump) y retorna de inmediato su ID
	CrearRespaldo(ctx context.Context, in *CrearRespaldoRequest, opts ...grpc.CallOption) (*CrearRespaldoResponse, error)
	// Consulta el estado detallado de una operación de respaldo
	ObtenerRespaldo(ctx context.Context, in *ObtenerRespaldoRequest, opts ...grpc.CallOption) (*ObtenerRespaldoResponse, error)
	// Lista los respaldos registrados, del más reciente al más antiguo
	ListarRespaldos(ctx context.Context, in *ListarRespaldosRequest, opts ...grpc.CallOption) (*ListarRespaldosResponse, error)
	// Descarga el contenido binario del archivo .dump (base64 en JSON)
	DescargarRespaldo(ctx context.Context, in *DescargarRespaldoRequest, opts ...grpc.CallOption) (*DescargarRespaldoResponse, error)
	// Restaura la base de datos desde un respaldo COMPLETADO (operación destructiva,
	// requiere confirmación explícita; ejecuta pg_restore con --clean --if-exists)
	RestaurarRespaldo(ctx context.Context, in *RestaurarRespaldoRequest, opts ...grpc.CallOption) (*RestaurarRespaldoResponse, error)
	// Elimina archivos y registros de respaldos vencidos según la política indicada
	AplicarRetencion(ctx context.Context, in *AplicarRetencionRequest, opts ...grpc.CallOption) (*AplicarRetencionResponse, error)
}

type respaldoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRespaldoServiceClient(cc grpc.ClientConnInterface) RespaldoServiceClient {
	return &respaldoServiceClient{cc}
}

func (c *respaldoServiceClient) CrearRespaldo(ctx context.Context, in *CrearRespaldoRequest, opts ...grpc.CallOption) (*CrearRespaldoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CrearRespaldoResponse)
	err := c.cc.Invoke(ctx, RespaldoService_CrearRespaldo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *respaldoServiceClient) ObtenerRespaldo(ctx context.Context, in *ObtenerRespaldoRequest, opts ...grpc.CallOption) (*ObtenerRespaldoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ObtenerRespaldoResponse)
	err := c.cc.Invoke(ctx, RespaldoService_ObtenerRespaldo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *respaldoServiceClient) ListarRespaldos(ctx context.Context, in *ListarRespaldosRequest, opts ...grpc.CallOption) (*ListarRespaldosResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListarRespaldosResponse)
	err := c.cc.Invoke(ctx, RespaldoService_ListarRespaldos_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *respaldoServiceClient) DescargarRespaldo(ctx context.Context, in *DescargarRespaldoRequest, opts ...grpc.CallOption) (*DescargarRespaldoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DescargarRespaldoResponse)
	err := c.cc.Invoke(ctx, RespaldoService_DescargarRespaldo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *respaldoServiceClient) RestaurarRespaldo(ctx context.Context, in *RestaurarRespaldoRequest, opts ...grpc.CallOption) (*RestaurarRespaldoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RestaurarRespaldoResponse)
	err := c.cc.Invoke(ctx, RespaldoService_RestaurarRespaldo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *respaldoServiceClient) AplicarRetencion(ctx context.Context, in *AplicarRetencionRequest, opts ...grpc.CallOption) (*AplicarRetencionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AplicarRetencionResponse)
	err := c.cc.Invoke(ctx, RespaldoService_AplicarRetencion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RespaldoServiceServer is the server API for RespaldoService service.
// All implementations must embed UnimplementedRespaldoServiceServer
// for forward compatibility.
//
// Servicio de Respaldos y Operación (Dominio 8).
// Orquesta pg_dump/pg_restore mediante los scripts oficiales en db/backup,
// registra cada operación en la bitácora y expone la política de retención.
//
// NOTA DE SEGURIDAD: Todos los métodos requieren autenticación (JWT o API Key).
// La creación/descarga exige el permiso 'respaldo:ejecutar' y la restauración
// exige 'restauracion:ejecutar' (ver db/seeds/seed_users.sql).
type RespaldoServiceServer interface {
	// Lanza un respaldo completo asíncrono (pg_dump) y retorna de inmediato su ID
	CrearRespaldo(context.Context, *CrearRespaldoRequest) (*CrearRespaldoResponse, error)
	// Consulta el estado detallado de una operación de respaldo
	ObtenerRespaldo(context.Context, *ObtenerRespaldoRequest) (*ObtenerRespaldoResponse, error)
	// Lista los respaldos registrados, del más reciente al más antiguo
	ListarRespaldos(context.Context, *ListarRespaldosRequest) (*ListarRespaldosResponse, error)
	// Descarga el contenido binario del archivo .dump (base64 en JSON)
	DescargarRespaldo(context.Context, *DescargarRespaldoRequest) (*DescargarRespaldoResponse, error)
	// Restaura la base de datos desde un respaldo COMPLETADO (operación destructiva,
	// requiere confirmación explícita; ejecuta pg_restore con --clean --if-exists)
	RestaurarRespaldo(context.Context, *RestaurarRespaldoRequest) (*RestaurarRespaldoResponse, error)
	// Elimina archivos y registros de respaldos vencidos según la política indicada
	AplicarRetencion(context.Context, *AplicarRetencionRequest) (*AplicarRetencionResponse, error)
	mustEmbedUnimplementedRespaldoServiceServer()
}

// UnimplementedRespaldoServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRespaldoServiceServer struct{}

func (UnimplementedRespaldoServiceServer) CrearRespaldo(context.Context, *CrearRespaldoRequest) (*CrearRespaldoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CrearRespaldo not implemented")
}
func (UnimplementedRespaldoServiceServer) ObtenerRespaldo(context.Context, *ObtenerRespaldoRequest) (*ObtenerRespaldoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ObtenerRespaldo not implemented")
}
func (UnimplementedRespaldoServiceServer) ListarRespaldos(context.Context, *ListarRespaldosRequest) (*ListarRespaldosResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListarRespaldos not implemented")
}
func (UnimplementedRespaldoServiceServer) DescargarRespaldo(context.Context, *DescargarRespaldoRequest) (*DescargarRespaldoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DescargarRespaldo not implemented")
}
func (UnimplementedRespaldoServiceServer) RestaurarRespaldo(context.Context, *RestaurarRespaldoRequest) (*RestaurarRespaldoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RestaurarRespaldo not implemented")
}
func (UnimplementedRespaldoServiceServer) AplicarRetencion(context.Context, *AplicarRetencionRequest) (*AplicarRetencionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AplicarRetencion not implemented")
}
func (UnimplementedRespaldoServiceServer) mustEmbedUnimplementedRespaldoServiceServer() {}
func (UnimplementedRespaldoServiceServer) testEmbeddedByValue()                         {}

// UnsafeRespaldoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RespaldoServiceServer will
// result in compilation errors.
type UnsafeRespaldoServiceServer interface {
	mustEmbedUnimplementedRespaldoServiceServer()
}

func RegisterRespaldoServiceServer(s grpc.ServiceRegistrar, srv RespaldoServiceServer) {
	// If the following call panics, it indicates UnimplementedRespaldoServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RespaldoService_ServiceDesc, srv)
}

func _RespaldoService_CrearRespaldo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CrearRespaldoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RespaldoServiceServer).CrearRespaldo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RespaldoService_CrearRespaldo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RespaldoServiceServer).CrearRespaldo(ctx, req.(*CrearRespaldoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RespaldoService_ObtenerRespaldo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ObtenerRespaldoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RespaldoServiceServer).ObtenerRespaldo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RespaldoService_ObtenerRespaldo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RespaldoServiceServer).ObtenerRespaldo(ctx, req.(*ObtenerRespaldoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RespaldoService_ListarRespaldos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListarRespaldosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RespaldoServiceServer).ListarRespaldos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RespaldoService_ListarRespaldos_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RespaldoServiceServer).ListarRespaldos(ctx, req.(*ListarRespaldosRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RespaldoService_DescargarRespaldo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescargarRespaldoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RespaldoServiceServer).DescargarRespaldo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RespaldoService_DescargarRespaldo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RespaldoServiceServer).DescargarRespaldo(ctx, req.(*DescargarRespaldoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RespaldoService_RestaurarRespaldo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestaurarRespaldoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RespaldoServiceServer).RestaurarRespaldo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RespaldoService_RestaurarRespaldo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RespaldoServiceServer).RestaurarRespaldo(ctx, req.(*RestaurarRespaldoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RespaldoService_AplicarRetencion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AplicarRetencionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RespaldoServiceServer).AplicarRetencion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RespaldoService_AplicarRetencion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RespaldoServiceServer).AplicarRetencion(ctx, req.(*AplicarRetencionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RespaldoService_ServiceDesc is the grpc.ServiceDesc for RespaldoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RespaldoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dbgs.v1.RespaldoService",
	HandlerType: (*RespaldoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CrearRespaldo",
			Handler:    _RespaldoService_CrearRespaldo_Handler,
		},
		{
			MethodName: "ObtenerRespaldo",
			Handler:    _RespaldoService_ObtenerRespaldo_Handler,
		},
		{
			MethodName: "ListarRespaldos",
			Handler:    _RespaldoService_ListarRespaldos_Handler,
		},
		{
			MethodName: "DescargarRespaldo",
			Handler:    _RespaldoService_DescargarRespaldo_Handler,
		},
		{
			MethodName: "RestaurarRespaldo",
			Handler:    _RespaldoService_RestaurarRespaldo_Handler,
		},
		{
			MethodName: "AplicarRetencion",
			Handler:    _RespaldoService_AplicarRetencion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "respaldo_servicio.proto",
}
