// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: seguridad_servicio.proto

package dbgsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SeguridadService_GetSetupStatus_FullMethodName        = "/dbgs.v1.SeguridadService/GetSetupStatus"
	SeguridadService_CreateSetup_FullMethodName           = "/dbgs.v1.SeguridadService/CreateSetup"
	SeguridadService_Login_FullMethodName                 = "/dbgs.v1.SeguridadService/Login"
	SeguridadService_ValidarToken_FullMethodName          = "/dbgs.v1.SeguridadService/ValidarToken"
	SeguridadService_VerificarPermiso_FullMethodName      = "/dbgs.v1.SeguridadService/VerificarPermiso"
	SeguridadService_CrearRol_FullMethodName              = "/dbgs.v1.SeguridadService/CrearRol"
	SeguridadService_ListarRoles_FullMethodName           = "/dbgs.v1.SeguridadService/ListarRoles"
	SeguridadService_ObtenerRol_FullMethodName            = "/dbgs.v1.SeguridadService/ObtenerRol"
	SeguridadService_ActualizarRol_FullMethodName         = "/dbgs.v1.SeguridadService/ActualizarRol"
	SeguridadService_EliminarRol_FullMethodName           = "/dbgs.v1.SeguridadService/EliminarRol"
	SeguridadService_VincularPermisoRol_FullMethodName    = "/dbgs.v1.SeguridadService/VincularPermisoRol"
	SeguridadService_DesvincularPermisoRol_FullMethodName = "/dbgs.v1.SeguridadService/DesvincularPermisoRol"
	SeguridadService_ListarPermisosRol_FullMethodName     = "/dbgs.v1.SeguridadService/ListarPermisosRol"
)

// SeguridadServiceClient is the client API for SeguridadService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Servicio gRPC para autenticación, RBAC, validación de tokens y configuración inicial
type SeguridadServiceClient interface {
	// Verifica si el sistema ya ha sido inicializado (existe al menos un SUPER_ADMIN)
	GetSetupStatus(ctx context.Context, in *GetSetupStatusRequest, opts ...grpc.CallOption) (*GetSetupStatusResponse, error)
	// Crea el primer usuario SUPER_ADMIN. Solo se permite si el sistema no está inicializado.
	CreateSetup(ctx context.Context, in *CreateSetupRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	// Expone el endpoint como POST. 'body: "*"' indica que todo el JSON va en el cuerpo de la petición.
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	ValidarToken(ctx context.Context, in *ValidarTokenRequest, opts ...grpc.CallOption) (*ValidarTokenResponse, error)
	VerificarPermiso(ctx context.Context, in *VerificarPermisoRequest, opts ...grpc.CallOption) (*VerificarPermisoResponse, error)
	CrearRol(ctx context.Context, in *CrearRolRequest, opts ...grpc.CallOption) (*CrearRolResponse, error)
	ListarRoles(ctx context.Context, in *ListarRolesRequest, opts ...grpc.CallOption) (*ListarRolesResponse, error)
	ObtenerRol(ctx context.Context, in *ObtenerRolRequest, opts ...grpc.CallOption) (*ObtenerRolResponse, error)
	ActualizarRol(ctx context.Context, in *ActualizarRolRequest, opts ...grpc.CallOption) (*ActualizarRolResponse, error)
	EliminarRol(ctx context.Context, in *EliminarRolRequest, opts ...grpc.CallOption) (*EliminarRolResponse, error)
	VincularPermisoRol(ctx context.Context, in *VincularPermisoRolRequest, opts ...grpc.CallOption) (*VincularPermisoRolResponse, error)
	DesvincularPermisoRol(ctx context.Context, in *DesvincularPermisoRolRequest, opts ...grpc.CallOption) (*DesvincularPermisoRolResponse, error)
	ListarPermisosRol(ctx context.Context, in *ListarPermisosRolRequest, opts ...grpc.CallOption) (*ListarPermisosRolResponse, error)
}

type seguridadServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSeguridadServiceClient(cc grpc.ClientConnInterface) SeguridadServiceClient {
	return &seguridadServiceClient{cc}
}

func (c *seguridadServiceClient) GetSetupStatus(ctx context.Context, in *GetSetupStatusRequest, opts ...grpc.CallOption) (*GetSetupStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSetupStatusResponse)
	err := c.cc.Invoke(ctx, SeguridadService_GetSetupStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seguridadServiceClient) CreateSetup(ctx context.Context, in *CreateSetupRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, SeguridadService_CreateSetup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seguridadServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, SeguridadService_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seguridadServiceClient) ValidarToken(ctx context.Context, in *ValidarTokenRequest, opts ...grpc.CallOption) (*ValidarTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidarTokenResponse)
	err := c.cc.Invoke(ctx, SeguridadService_ValidarToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seguridadServiceClient) VerificarPermiso(ctx context.Context, in *VerificarPermisoRequest, opts ...grpc.CallOption) (*VerificarPermisoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerificarPermisoResponse)
	err := c.cc.Invoke(ctx, SeguridadService_VerificarPermiso_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seguridadServiceClient) CrearRol(ctx context.Context, in *CrearRolRequest, opts ...grpc.CallOption) (*CrearRolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CrearRolResponse)
	err := c.cc.Invoke(ctx, SeguridadService_CrearRol_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seguridadServiceClient) ListarRoles(ctx context.Context, in *ListarRolesRequest, opts ...grpc.CallOption) (*ListarRolesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListarRolesResponse)
	err := c.cc.Invoke(ctx, SeguridadService_ListarRoles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seguridadServiceClient) ObtenerRol(ctx context.Context, in *ObtenerRolRequest, opts ...grpc.CallOption) (*ObtenerRolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ObtenerRolResponse)
	err := c.cc.Invoke(ctx, SeguridadService_ObtenerRol_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seguridadServiceClient) ActualizarRol(ctx context.Context, in *ActualizarRolRequest, opts ...grpc.CallOption) (*ActualizarRolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActualizarRolResponse)
	err := c.cc.Invoke(ctx, SeguridadService_ActualizarRol_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seguridadServiceClient) EliminarRol(ctx context.Context, in *EliminarRolRequest, opts ...grpc.CallOption) (*EliminarRolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EliminarRolResponse)
	err := c.cc.Invoke(ctx, SeguridadService_EliminarRol_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seguridadServiceClient) VincularPermisoRol(ctx context.Context, in *VincularPermisoRolRequest, opts ...grpc.CallOption) (*VincularPermisoRolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VincularPermisoRolResponse)
	err := c.cc.Invoke(ctx, SeguridadService_VincularPermisoRol_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seguridadServiceClient) DesvincularPermisoRol(ctx context.Context, in *DesvincularPermisoRolRequest, opts ...grpc.CallOption) (*DesvincularPermisoRolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DesvincularPermisoRolResponse)
	err := c.cc.Invoke(ctx, SeguridadService_DesvincularPermisoRol_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seguridadServiceClient) ListarPermisosRol(ctx context.Context, in *ListarPermisosRolRequest, opts ...grpc.CallOption) (*ListarPermisosRolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListarPermisosRolResponse)
	err := c.cc.Invoke(ctx, SeguridadService_ListarPermisosRol_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SeguridadServiceServer is the server API for SeguridadService service.
// All implementations must embed UnimplementedSeguridadServiceServer
// for forward compatibility.
//
// Servicio gRPC para autenticación, RBAC, validación de tokens y configuración inicial
type SeguridadServiceServer interface {
	// Verifica si el sistema ya ha sido inicializado (existe al menos un SUPER_ADMIN)
	GetSetupStatus(context.Context, *GetSetupStatusRequest) (*GetSetupStatusResponse, error)
	// Crea el primer usuario SUPER_ADMIN. Solo se permite si el sistema no está inicializado.
	CreateSetup(context.Context, *CreateSetupRequest) (*LoginResponse, error)
	// Expone el endpoint como POST. 'body: "*"' indica que todo el JSON va en el cuerpo de la petición.
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	ValidarToken(context.Context, *ValidarTokenRequest) (*ValidarTokenResponse, error)
	VerificarPermiso(context.Context, *VerificarPermisoRequest) (*VerificarPermisoResponse, error)
	CrearRol(context.Context, *CrearRolRequest) (*CrearRolResponse, error)
	ListarRoles(context.Context, *ListarRolesRequest) (*ListarRolesResponse, error)
	ObtenerRol(context.Context, *ObtenerRolRequest) (*ObtenerRolResponse, error)
	ActualizarRol(context.Context, *ActualizarRolRequest) (*ActualizarRolResponse, error)
	EliminarRol(context.Context, *EliminarRolRequest) (*EliminarRolResponse, error)
	VincularPermisoRol(context.Context, *VincularPermisoRolRequest) (*VincularPermisoRolResponse, error)
	DesvincularPermisoRol(context.Context, *DesvincularPermisoRolRequest) (*DesvincularPermisoRolResponse, error)
	ListarPermisosRol(context.Context, *ListarPermisosRolRequest) (*ListarPermisosRolResponse, error)
	mustEmbedUnimplementedSeguridadServiceServer()
}

// UnimplementedSeguridadServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSeguridadServiceServer struct{}

func (UnimplementedSeguridadServiceServer) GetSetupStatus(context.Context, *GetSetupStatusRequest) (*GetSetupStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSetupStatus not implemented")
}
func (UnimplementedSeguridadServiceServer) CreateSetup(context.Context, *CreateSetupRequest) (*LoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSetup not implemented")
}
func (UnimplementedSeguridadServiceServer) Login(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedSeguridadServiceServer) ValidarToken(context.Context, *ValidarTokenRequest) (*ValidarTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidarToken not implemented")
}
func (UnimplementedSeguridadServiceServer) VerificarPermiso(context.Context, *VerificarPermisoRequest) (*VerificarPermisoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerificarPermiso not implemented")
}
func (UnimplementedSeguridadServiceServer) CrearRol(context.Context, *CrearRolRequest) (*CrearRolResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CrearRol not implemented")
}
func (UnimplementedSeguridadServiceServer) ListarRoles(context.Context, *ListarRolesRequest) (*ListarRolesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListarRoles not implemented")
}
func (UnimplementedSeguridadServiceServer) ObtenerRol(context.Context, *ObtenerRolRequest) (*ObtenerRolResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ObtenerRol not implemented")
}
func (UnimplementedSeguridadServiceServer) ActualizarRol(context.Context, *ActualizarRolRequest) (*ActualizarRolResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ActualizarRol not implemented")
}
func (UnimplementedSeguridadServiceServer) EliminarRol(context.Context, *EliminarRolRequest) (*EliminarRolResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EliminarRol not implemented")
}
func (UnimplementedSeguridadServiceServer) VincularPermisoRol(context.Context, *VincularPermisoRolRequest) (*VincularPermisoRolResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VincularPermisoRol not implemented")
}
func (UnimplementedSeguridadServiceServer) DesvincularPermisoRol(context.Context, *DesvincularPermisoRolRequest) (*DesvincularPermisoRolResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DesvincularPermisoRol not implemented")
}
func (UnimplementedSeguridadServiceServer) ListarPermisosRol(context.Context, *ListarPermisosRolRequest) (*ListarPermisosRolResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListarPermisosRol not implemented")
}
func (UnimplementedSeguridadServiceServer) mustEmbedUnimplementedSeguridadServiceServer() {}
func (UnimplementedSeguridadServiceServer) testEmbeddedByValue()                          {}

// UnsafeSeguridadServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SeguridadServiceServer will
// result in compilation errors.
type UnsafeSeguridadServiceServer interface {
	mustEmbedUnimplementedSeguridadServiceServer()
}

func RegisterSeguridadServiceServer(s grpc.ServiceRegistrar, srv SeguridadServiceServer) {
	// If the following call panics, it indicates UnimplementedSeguridadServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SeguridadService_ServiceDesc, srv)
}

func _SeguridadService_GetSetupStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSetupStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeguridadServiceServer).GetSetupStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SeguridadService_GetSetupStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeguridadServiceServer).GetSetupStatus(ctx, req.(*GetSetupStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SeguridadService_CreateSetup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSetupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeguridadServiceServer).CreateSetup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SeguridadService_CreateSetup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeguridadServiceServer).CreateSetup(ctx, req.(*CreateSetupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SeguridadService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeguridadServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SeguridadService_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeguridadServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SeguridadService_ValidarToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidarTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeguridadServiceServer).ValidarToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SeguridadService_ValidarToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeguridadServiceServer).ValidarToken(ctx, req.(*ValidarTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SeguridadService_VerificarPermiso_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerificarPermisoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeguridadServiceServer).VerificarPermiso(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SeguridadService_VerificarPermiso_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeguridadServiceServer).VerificarPermiso(ctx, req.(*VerificarPermisoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SeguridadService_CrearRol_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CrearRolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeguridadServiceServer).CrearRol(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SeguridadService_CrearRol_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeguridadServiceServer).CrearRol(ctx, req.(*CrearRolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SeguridadService_ListarRoles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListarRolesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeguridadServiceServer).ListarRoles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SeguridadService_ListarRoles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeguridadServiceServer).ListarRoles(ctx, req.(*ListarRolesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SeguridadService_ObtenerRol_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ObtenerRolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeguridadServiceServer).ObtenerRol(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SeguridadService_ObtenerRol_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeguridadServiceServer).ObtenerRol(ctx, req.(*ObtenerRolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SeguridadService_ActualizarRol_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActualizarRolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeguridadServiceServer).ActualizarRol(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SeguridadService_ActualizarRol_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeguridadServiceServer).ActualizarRol(ctx, req.(*ActualizarRolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SeguridadService_EliminarRol_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EliminarRolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeguridadServiceServer).EliminarRol(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SeguridadService_EliminarRol_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeguridadServiceServer).EliminarRol(ctx, req.(*EliminarRolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SeguridadService_VincularPermisoRol_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VincularPermisoRolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeguridadServiceServer).VincularPermisoRol(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SeguridadService_VincularPermisoRol_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeguridadServiceServer).VincularPermisoRol(ctx, req.(*VincularPermisoRolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SeguridadService_DesvincularPermisoRol_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DesvincularPermisoRolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeguridadServiceServer).DesvincularPermisoRol(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SeguridadService_DesvincularPermisoRol_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeguridadServiceServer).DesvincularPermisoRol(ctx, req.(*DesvincularPermisoRolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SeguridadService_ListarPermisosRol_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListarPermisosRolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeguridadServiceServer).ListarPermisosRol(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SeguridadService_ListarPermisosRol_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeguridadServiceServer).ListarPermisosRol(ctx, req.(*ListarPermisosRolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SeguridadService_ServiceDesc is the grpc.ServiceDesc for SeguridadService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SeguridadService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dbgs.v1.SeguridadService",
	HandlerType: (*SeguridadServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSetupStatus",
			Handler:    _SeguridadService_GetSetupStatus_Handler,
		},
		{
			MethodName: "CreateSetup",
			Handler:    _SeguridadService_CreateSetup_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _SeguridadService_Login_Handler,
		},
		{
			MethodName: "ValidarToken",
			Handler:    _SeguridadService_ValidarToken_Handler,
		},
		{
			MethodName: "VerificarPermiso",
			Handler:    _SeguridadService_VerificarPermiso_Handler,
		},
		{
			MethodName: "CrearRol",
			Handler:    _SeguridadService_CrearRol_Handler,
		},
		{
			MethodName: "ListarRoles",
			Handler:    _SeguridadService_ListarRoles_Handler,
		},
		{
			MethodName: "ObtenerRol",
			Handler:    _SeguridadService_ObtenerRol_Handler,
		},
		{
			MethodName: "ActualizarRol",
			Handler:    _SeguridadService_ActualizarRol_Handler,
		},
		{
			MethodName: "EliminarRol",
			Handler:    _SeguridadService_EliminarRol_Handler,
		},
		{
			MethodName: "VincularPermisoRol",
			Handler:    _SeguridadService_VincularPermisoRol_Handler,
		},
		{
			MethodName: "DesvincularPermisoRol",
			Handler:    _SeguridadService_DesvincularPermisoRol_Handler,
		},
		{
			MethodName: "ListarPermisosRol",
			Handler:    _SeguridadService_ListarPermisosRol_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "seguridad_servicio.proto",
}
