// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: seguridad_servicio.proto

package dbgsv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetSetupStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSetupStatusRequest) Reset() {
	*x = GetSetupStatusRequest{}
	mi := &file_seguridad_servicio_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSetupStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSetupStatusRequest) ProtoMessage() {}

func (x *GetSetupStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_seguridad_servicio_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSetupStatusRequest.ProtoReflect.Descriptor instead.
func (*GetSetupStatusRequest) Descriptor() ([]byte, []int) {
	return file_seguridad_servicio_proto_rawDescGZIP(), []int{0}
}

type GetSetupStatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Indica si ya existe al menos un administrador principal en el sistema
	Initialized   bool `protobuf:"varint,1,opt,name=initialized,proto3" json:"initialized,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSetupStatusResponse) Reset() {
	*x = GetSetupStatusResponse{}
	mi := &file_seguridad_servicio_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSetupStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSetupStatusResponse) ProtoMessage() {}

func (x *GetSetupStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_seguridad_servicio_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSetupStatusResponse.ProtoReflect.Descriptor instead.
func (*GetSetupStatusResponse) Descriptor() ([]byte, []int) {
	return file_seguridad_servicio_proto_rawDescGZIP(), []int{1}
}

func (x *GetSetupStatusResponse) GetInitialized() bool {
	if x != nil {
		return x.Initialized
	}
	return false
}

type CreateSetupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSetupRequest) Reset() {
	*x = CreateSetupRequest{}
	mi := &file_seguridad_servicio_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSetupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSetupRequest) ProtoMessage() {}

func (x *CreateSetupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_seguridad_servicio_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSetupRequest.ProtoReflect.Descriptor instead.
func (*CreateSetupRequest) Descriptor() ([]byte, []int) {
	return file_seguridad_servicio_proto_rawDescGZIP(), []int{2}
}

func (x *CreateSetupRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateSetupRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateSetupRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_seguridad_servicio_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_seguridad_servicio_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_seguridad_servicio_proto_rawDescGZIP(), []int{3}
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	ExpiresIn     int64                  `protobuf:"varint,3,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	TokenType     string                 `protobuf:"bytes,4,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_seguridad_servicio_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_seguridad_servicio_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_seguridad_servicio_proto_rawDescGZIP(), []int{4}
}

func (x *LoginResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LoginResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *LoginResponse) GetExpiresIn() int64 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

func (x *LoginResponse) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

type ValidarTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidarTokenRequest) Reset() {
	*x = ValidarTokenRequest{}
	mi := &file_seguridad_servicio_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidarTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidarTokenRequest) ProtoMessage() {}

func (x *ValidarTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_seguridad_servicio_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidarTokenRequest.ProtoReflect.Descriptor instead.
func (*ValidarTokenRequest) Descriptor() ([]byte, []int) {
	return file_seguridad_servicio_proto_rawDescGZIP(), []int{5}
}

func (x *ValidarTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ValidarTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EsValido      bool                   `protobuf:"varint,1,opt,name=es_valido,json=esValido,proto3" json:"es_valido,omitempty"`
	UsuarioId     string                 `protobuf:"bytes,2,opt,name=usuario_id,json=usuarioId,proto3" json:"usuario_id,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Rol           string                 `protobuf:"bytes,4,opt,name=rol,proto3" json:"rol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidarTokenResponse) Reset() {
	*x = ValidarTokenResponse{}
	mi := &file_seguridad_servicio_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidarTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidarTokenResponse) ProtoMessage() {}

func (x *ValidarTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_seguridad_servicio_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidarTokenResponse.ProtoReflect.Descriptor instead.
func (*ValidarTokenResponse) Descriptor() ([]byte, []int) {
	return file_seguridad_servicio_proto_rawDescGZIP(), []int{6}
}

func (x *ValidarTokenResponse) GetEsValido() bool {
	if x != nil {
		return x.EsValido
	}
	return false
}

func (x *ValidarTokenResponse) GetUsuarioId() string {
	if x != nil {
		return x.UsuarioId
	}
	return ""
}

func (x *ValidarTokenResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ValidarTokenResponse) GetRol() string {
	if x != nil {
		return x.Rol
	}
	return ""
}

type VerificarPermisoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UsuarioId     string                 `protobuf:"bytes,1,opt,name=usuario_id,json=usuarioId,proto3" json:"usuario_id,omitempty"`
	Recurso       string                 `protobuf:"bytes,2,opt,name=recurso,proto3" json:"recurso,omitempty"`
	Accion        string                 `protobuf:"bytes,3,opt,name=accion,proto3" json:"accion,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerificarPermisoRequest) Reset() {
	*x = VerificarPermisoRequest{}
	mi := &file_seguridad_servicio_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerificarPermisoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerificarPermisoRequest) ProtoMessage() {}

func (x *VerificarPermisoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_seguridad_servicio_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerificarPermisoRequest.ProtoReflect.Descriptor instead.
func (*VerificarPermisoRequest) Descriptor() ([]byte, []int) {
	return file_seguridad_servicio_proto_rawDescGZIP(), []int{7}
}

func (x *VerificarPermisoRequest) GetUsuarioId() string {
	if x != nil {
		return x.UsuarioId
	}
	return ""
}

func (x *VerificarPermisoRequest) GetRecurso() string {
	if x != nil {
		return x.Recurso
	}
	return ""
}

func (x *VerificarPermisoRequest) GetAccion() string {
	if x != nil {
		return x.Accion
	}
	return ""
}

type VerificarPermisoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Permitido     bool                   `protobuf:"varint,1,opt,name=permitido,proto3" json:"permitido,omitempty"`
	Razon         string                 `protobuf:"bytes,2,opt,name=razon,proto3" json:"razon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerificarPermisoResponse) Reset() {
	*x = VerificarPermisoResponse{}
	mi := &file_seguridad_servicio_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerificarPermisoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerificarPermisoResponse) ProtoMessage() {}

func (x *VerificarPermisoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_seguridad_servicio_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerificarPermisoResponse.ProtoReflect.Descriptor instead.
func (*VerificarPermisoResponse) Descriptor() ([]byte, []int) {
	return file_seguridad_servicio_proto_rawDescGZIP(), []int{8}
}

func (x *VerificarPermisoResponse) GetPermitido() bool {
	if x != nil {
		return x.Permitido
	}
	return false
}

func (x *VerificarPermisoResponse) GetRazon() string {
	if x != nil {
		return x.Razon
	}
	return ""
}

var File_seguridad_servicio_proto protoreflect.FileDescriptor

const file_seguridad_servicio_proto_rawDesc = "" +
	"\n" +
	"\x18seguridad_servicio.proto\x12\adbgs.v1\x1a\x1cgoogle/api/annotations.proto\"\x17\n" +
	"\x15GetSetupStatusRequest\":\n" +
	"\x16GetSetupStatusResponse\x12 \n" +
	"\vinitialized\x18\x01 \x01(\bR\vinitialized\"b\n" +
	"\x12CreateSetupRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\"F\n" +
	"\fLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\x95\x01\n" +
	"\rLoginResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x03 \x01(\x03R\texpiresIn\x12\x1d\n" +
	"\n" +
	"token_type\x18\x04 \x01(\tR\ttokenType\"+\n" +
	"\x13ValidarTokenRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\x80\x01\n" +
	"\x14ValidarTokenResponse\x12\x1b\n" +
	"\tes_valido\x18\x01 \x01(\bR\besValido\x12\x1d\n" +
	"\n" +
	"usuario_id\x18\x02 \x01(\tR\tusuarioId\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x10\n" +
	"\x03rol\x18\x04 \x01(\tR\x03rol\"j\n" +
	"\x17VerificarPermisoRequest\x12\x1d\n" +
	"\n" +
	"usuario_id\x18\x01 \x01(\tR\tusuarioId\x12\x18\n" +
	"\arecurso\x18\x02 \x01(\tR\arecurso\x12\x16\n" +
	"\x06accion\x18\x03 \x01(\tR\x06accion\"N\n" +
	"\x18VerificarPermisoResponse\x12\x1c\n" +
	"\tpermitido\x18\x01 \x01(\bR\tpermitido\x12\x14\n" +
	"\x05razon\x18\x02 \x01(\tR\x05razon2\xb6\x04\n" +
	"\x10SeguridadService\x12p\n" +
	"\x0eGetSetupStatus\x12\x1e.dbgs.v1.GetSetupStatusRequest\x1a\x1f.dbgs.v1.GetSetupStatusResponse\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/v1/auth/setup-status\x12]\n" +
	"\vCreateSetup\x12\x1b.dbgs.v1.CreateSetupRequest\x1a\x16.dbgs.v1.LoginResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/auth/setup\x12V\n" +
	"\x05Login\x12\x15.dbgs.v1.LoginRequest\x1a\x16.dbgs.v1.LoginResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/v1/seguridad/login\x12s\n" +
	"\fValidarToken\x12\x1c.dbgs.v1.ValidarTokenRequest\x1a\x1d.dbgs.v1.ValidarTokenResponse\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/v1/seguridad/validar-token\x12\x83\x01\n" +
	"\x10VerificarPermiso\x12 .dbgs.v1.VerificarPermisoRequest\x1a!.dbgs.v1.VerificarPermisoResponse\"*\x82\xd3\xe4\x93\x02$:\x01*\"\x1f/v1/seguridad/verificar-permisoB+Z)DBGS_SOBERANO_BACKEND/api/proto/v1;dbgsv1b\x06proto3"

var (
	file_seguridad_servicio_proto_rawDescOnce sync.Once
	file_seguridad_servicio_proto_rawDescData []byte
)

func file_seguridad_servicio_proto_rawDescGZIP() []byte {
	file_seguridad_servicio_proto_rawDescOnce.Do(func() {
		file_seguridad_servicio_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_seguridad_servicio_proto_rawDesc), len(file_seguridad_servicio_proto_rawDesc)))
	})
	return file_seguridad_servicio_proto_rawDescData
}

var file_seguridad_servicio_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_seguridad_servicio_proto_goTypes = []any{
	(*GetSetupStatusRequest)(nil),    // 0: dbgs.v1.GetSetupStatusRequest
	(*GetSetupStatusResponse)(nil),   // 1: dbgs.v1.GetSetupStatusResponse
	(*CreateSetupRequest)(nil),       // 2: dbgs.v1.CreateSetupRequest
	(*LoginRequest)(nil),             // 3: dbgs.v1.LoginRequest
	(*LoginResponse)(nil),            // 4: dbgs.v1.LoginResponse
	(*ValidarTokenRequest)(nil),      // 5: dbgs.v1.ValidarTokenRequest
	(*ValidarTokenResponse)(nil),     // 6: dbgs.v1.ValidarTokenResponse
	(*VerificarPermisoRequest)(nil),  // 7: dbgs.v1.VerificarPermisoRequest
	(*VerificarPermisoResponse)(nil), // 8: dbgs.v1.VerificarPermisoResponse
}
var file_seguridad_servicio_proto_depIdxs = []int32{
	0, // 0: dbgs.v1.SeguridadService.GetSetupStatus:input_type -> dbgs.v1.GetSetupStatusRequest
	2, // 1: dbgs.v1.SeguridadService.CreateSetup:input_type -> dbgs.v1.CreateSetupRequest
	3, // 2: dbgs.v1.SeguridadService.Login:input_type -> dbgs.v1.LoginRequest
	5, // 3: dbgs.v1.SeguridadService.ValidarToken:input_type -> dbgs.v1.ValidarTokenRequest
	7, // 4: dbgs.v1.SeguridadService.VerificarPermiso:input_type -> dbgs.v1.VerificarPermisoRequest
	1, // 5: dbgs.v1.SeguridadService.GetSetupStatus:output_type -> dbgs.v1.GetSetupStatusResponse
	4, // 6: dbgs.v1.SeguridadService.CreateSetup:output_type -> dbgs.v1.LoginResponse
	4, // 7: dbgs.v1.SeguridadService.Login:output_type -> dbgs.v1.LoginResponse
	6, // 8: dbgs.v1.SeguridadService.ValidarToken:output_type -> dbgs.v1.ValidarTokenResponse
	8, // 9: dbgs.v1.SeguridadService.VerificarPermiso:output_type -> dbgs.v1.VerificarPermisoResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_seguridad_servicio_proto_init() }
func file_seguridad_servicio_proto_init() {
	if File_seguridad_servicio_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_seguridad_servicio_proto_rawDesc), len(file_seguridad_servicio_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_seguridad_servicio_proto_goTypes,
		DependencyIndexes: file_seguridad_servicio_proto_depIdxs,
		MessageInfos:      file_seguridad_servicio_proto_msgTypes,
	}.Build()
	File_seguridad_servicio_proto = out.File
	file_seguridad_servicio_proto_goTypes = nil
	file_seguridad_servicio_proto_depIdxs = nil
}
