// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: seguridad_servicio.proto

package dbgsv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetSetupStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSetupStatusRequest) Reset() {
	*x = GetSetupStatusRequest{}
	mi := &file_seguridad_servicio_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSetupStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSetupStatusRequest) ProtoMessage() {}

func (x *GetSetupStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_seguridad_servicio_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSetupStatusRequest.ProtoReflect.Descriptor instead.
func (*GetSetupStatusRequest) Descriptor() ([]byte, []int) {
	return file_seguridad_servicio_proto_rawDescGZIP(), []int{0}
}

type GetSetupStatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Indica si ya existe al menos un administrador principal en el sistema
	Initialized   bool `protobuf:"varint,1,opt,name=initialized,proto3" json:"initialized,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSetupStatusResponse) Reset() {
	*x = GetSetupStatusResponse{}
	mi := &file_seguridad_servicio_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSetupStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSetupStatusResponse) ProtoMessage() {}

func (x *GetSetupStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_seguridad_servicio_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSetupStatusResponse.ProtoReflect.Descriptor instead.
func (*GetSetupStatusResponse) Descriptor() ([]byte, []int) {
	return file_seguridad_servicio_proto_rawDescGZIP(), []int{1}
}

func (x *GetSetupStatusResponse) GetInitialized() bool {
	if x != nil {
		return x.Initialized
	}
	return false
}

type CreateSetupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSetupRequest) Reset() {
	*x = CreateSetupRequest{}
	mi := &file_seguridad_servicio_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSetupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSetupRequest) ProtoMessage() {}

func (x *CreateSetupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_seguridad_servicio_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSetupRequest.ProtoReflect.Descriptor instead.
func (*CreateSetupRequest) Descriptor() ([]byte, []int) {
	return file_seguridad_servicio_proto_rawDescGZIP(), []int{2}
}

func (x *CreateSetupRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateSetupRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateSetupRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_seguridad_servicio_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_seguridad_servicio_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_seguridad_servicio_proto_rawDescGZIP(), []int{3}
}

func (x *LoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	ExpiresIn     int64                  `protobuf:"varint,3,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	TokenType     string                 `protobuf:"bytes,4,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_seguridad_servicio_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_seguridad_servicio_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_seguridad_servicio_proto_rawDescGZIP(), []int{4}
}

func (x *LoginResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LoginResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *LoginResponse) GetExpiresIn() int64 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

func (x *LoginResponse) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

type ValidarTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidarTokenRequest) Reset() {
	*x = ValidarTokenRequest{}
	mi := &file_seguridad_servicio_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidarTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidarTokenRequest) ProtoMessage() {}

func (x *ValidarTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_seguridad_servicio_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidarTokenRequest.ProtoReflect.Descriptor instead.
func (*ValidarTokenRequest) Descriptor() ([]byte, []int) {
	return file_seguridad_servicio_proto_rawDescGZIP(), []int{5}
}

func (x *ValidarTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ValidarTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EsValido      bool                   `protobuf:"varint,1,opt,name=es_valido,json=esValido,proto3" json:"es_valido,omitempty"`
	UsuarioId     string                 `protobuf:"bytes,2,opt,name=usuario_id,json=usuarioId,proto3" json:"usuario_id,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Rol           string                 `protobuf:"bytes,4,opt,name=rol,proto3" json:"rol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidarTokenResponse) Reset() {
	*x = ValidarTokenResponse{}
	mi := &file_seguridad_servicio_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidarTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidarTokenResponse) ProtoMessage() {}

func (x *ValidarTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_seguridad_servicio_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidarTokenResponse.ProtoReflect.Descriptor instead.
func (*ValidarTokenResponse) Descriptor() ([]byte, []int) {
	return file_seguridad_servicio_proto_rawDescGZIP(), []int{6}
}

func (x *ValidarTokenResponse) GetEsValido() bool {
	if x != nil {
		return x.EsValido
	}
	return false
}

func (x *ValidarTokenResponse) GetUsuarioId() string {
	if x != nil {
		return x.UsuarioId
	}
	return ""
}

func (x *ValidarTokenResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ValidarTokenResponse) GetRol() string {
	if x != nil {
		return x.Rol
	}
	return ""
}

type VerificarPermisoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UsuarioId     string                 `protobuf:"bytes,1,opt,name=usuario_id,json=usuarioId,proto3" json:"usuario_id,omitempty"`
	Recurso       string                 `protobuf:"bytes,2,opt,name=recurso,proto3" json:"recurso,omitempty"`
	Accion        string                 `protobuf:"bytes,3,opt,name=accion,proto3" json:"accion,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerificarPermisoRequest) Reset() {
	*x = VerificarPermisoRequest{}
	mi := &file_seguridad_servicio_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerificarPermisoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerificarPermisoRequest) ProtoMessage() {}

func (x *VerificarPermisoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_seguridad_servicio_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerificarPermisoRequest.ProtoReflect.Descriptor instead.
func (*VerificarPermisoRequest) Descriptor() ([]byte, []int) {
	return file_seguridad_servicio_proto_rawDescGZIP(), []int{7}
}

func (x *VerificarPermisoRequest) GetUsuarioId() string {
	if x != nil {
		return x.UsuarioId
	}
	return ""
}

func (x *VerificarPermisoRequest) GetRecurso() string {
	if x != nil {
		return x.Recurso
	}
	return ""
}

func (x *VerificarPermisoRequest) GetAccion() string {
	if x != nil {
		return x.Accion
	}
	return ""
}

type VerificarPermisoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Permitido     bool                   `protobuf:"varint,1,opt,name=permitido,proto3" json:"permitido,omitempty"`
	Razon         string                 `protobuf:"bytes,2,opt,name=razon,proto3" json:"razon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerificarPermisoResponse) Reset() {
	*x = VerificarPermisoResponse{}
	mi := &file_seguridad_servicio_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerificarPermisoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerificarPermisoResponse) ProtoMessage() {}

func (x *VerificarPermisoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_seguridad_servicio_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerificarPermisoResponse.ProtoReflect.Descriptor instead.
func (*VerificarPermisoResponse) Descriptor() ([]byte, []int) {
	return file_seguridad_servicio_proto_rawDescGZIP(), []int{8}
}

func (x *VerificarPermisoResponse) GetPermitido() bool {
	if x != nil {
		return x.Permitido
	}
	return false
}

func (x *VerificarPermisoResponse) GetRazon() string {
	if x != nil {
		return x.Razon
	}
	return ""
}

type CrearRolRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nombre        string                 `protobuf:"bytes,1,opt,name=nombre,proto3" json:"nombre,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CrearRolRequest) Reset() {
	*x = CrearRolRequest{}
	mi := &file_seguridad_servicio_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrearRolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrearRolRequest) ProtoMessage() {}

func (x *CrearRolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_seguridad_servicio_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrearRolRequest.ProtoReflect.Descriptor instead.
func (*CrearRolRequest) Descriptor() ([]byte, []int) {
	return file_seguridad_servicio_proto_rawDescGZIP(), []int{9}
}

func (x *CrearRolRequest) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

func (x *CrearRolRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CrearRolResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Nombre        string                 `protobuf:"bytes,2,opt,name=nombre,proto3" json:"nombre,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Mensaje       string                 `protobuf:"bytes,4,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CrearRolResponse) Reset() {
	*x = CrearRolResponse{}
	mi := &file_seguridad_servicio_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrearRolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrearRolResponse) ProtoMessage() {}

func (x *CrearRolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_seguridad_servicio_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrearRolResponse.ProtoReflect.Descriptor instead.
func (*CrearRolResponse) Descriptor() ([]byte, []int) {
	return file_seguridad_servicio_proto_rawDescGZIP(), []int{10}
}

func (x *CrearRolResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CrearRolResponse) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

func (x *CrearRolResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CrearRolResponse) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

type ListarRolesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListarRolesRequest) Reset() {
	*x = ListarRolesRequest{}
	mi := &file_seguridad_servicio_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListarRolesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListarRolesRequest) ProtoMessage() {}

func (x *ListarRolesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_seguridad_servicio_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListarRolesRequest.ProtoReflect.Descriptor instead.
func (*ListarRolesRequest) Descriptor() ([]byte, []int) {
	return file_seguridad_servicio_proto_rawDescGZIP(), []int{11}
}

type RolProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Nombre        string                 `protobuf:"bytes,2,opt,name=nombre,proto3" json:"nombre,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RolProto) Reset() {
	*x = RolProto{}
	mi := &file_seguridad_servicio_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RolProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RolProto) ProtoMessage() {}

func (x *RolProto) ProtoReflect() protoreflect.Message {
	mi := &file_seguridad_servicio_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RolProto.ProtoReflect.Descriptor instead.
func (*RolProto) Descriptor() ([]byte, []int) {
	return file_seguridad_servicio_proto_rawDescGZIP(), []int{12}
}

func (x *RolProto) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RolProto) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

func (x *RolProto) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type ListarRolesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Roles         []*RolProto            `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListarRolesResponse) Reset() {
	*x = ListarRolesResponse{}
	mi := &file_seguridad_servicio_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListarRolesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListarRolesResponse) ProtoMessage() {}

func (x *ListarRolesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_seguridad_servicio_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListarRolesResponse.ProtoReflect.Descriptor instead.
func (*ListarRolesResponse) Descriptor() ([]byte, []int) {
	return file_seguridad_servicio_proto_rawDescGZIP(), []int{13}
}

func (x *ListarRolesResponse) GetRoles() []*RolProto {
	if x != nil {
		return x.Roles
	}
	return nil
}

type ObtenerRolRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObtenerRolRequest) Reset() {
	*x = ObtenerRolRequest{}
	mi := &file_seguridad_servicio_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObtenerRolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObtenerRolRequest) ProtoMessage() {}

func (x *ObtenerRolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_seguridad_servicio_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObtenerRolRequest.ProtoReflect.Descriptor instead.
func (*ObtenerRolRequest) Descriptor() ([]byte, []int) {
	return file_seguridad_servicio_proto_rawDescGZIP(), []int{14}
}

func (x *ObtenerRolRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ObtenerRolResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Nombre        string                 `protobuf:"bytes,2,opt,name=nombre,proto3" json:"nombre,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObtenerRolResponse) Reset() {
	*x = ObtenerRolResponse{}
	mi := &file_seguridad_servicio_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObtenerRolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObtenerRolResponse) ProtoMessage() {}

func (x *ObtenerRolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_seguridad_servicio_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObtenerRolResponse.ProtoReflect.Descriptor instead.
func (*ObtenerRolResponse) Descriptor() ([]byte, []int) {
	return file_seguridad_servicio_proto_rawDescGZIP(), []int{15}
}

func (x *ObtenerRolResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ObtenerRolResponse) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

func (x *ObtenerRolResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type ActualizarRolRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Nombre        string                 `protobuf:"bytes,2,opt,name=nombre,proto3" json:"nombre,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActualizarRolRequest) Reset() {
	*x = ActualizarRolRequest{}
	mi := &file_seguridad_servicio_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActualizarRolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActualizarRolRequest) ProtoMessage() {}

func (x *ActualizarRolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_seguridad_servicio_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActualizarRolRequest.ProtoReflect.Descriptor instead.
func (*ActualizarRolRequest) Descriptor() ([]byte, []int) {
	return file_seguridad_servicio_proto_rawDescGZIP(), []int{16}
}

func (x *ActualizarRolRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ActualizarRolRequest) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

func (x *ActualizarRolRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type ActualizarRolResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Nombre        string                 `protobuf:"bytes,2,opt,name=nombre,proto3" json:"nombre,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Mensaje       string                 `protobuf:"bytes,4,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActualizarRolResponse) Reset() {
	*x = ActualizarRolResponse{}
	mi := &file_seguridad_servicio_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActualizarRolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActualizarRolResponse) ProtoMessage() {}

func (x *ActualizarRolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_seguridad_servicio_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActualizarRolResponse.ProtoReflect.Descriptor instead.
func (*ActualizarRolResponse) Descriptor() ([]byte, []int) {
	return file_seguridad_servicio_proto_rawDescGZIP(), []int{17}
}

func (x *ActualizarRolResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ActualizarRolResponse) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

func (x *ActualizarRolResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ActualizarRolResponse) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

type EliminarRolRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EliminarRolRequest) Reset() {
	*x = EliminarRolRequest{}
	mi := &file_seguridad_servicio_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EliminarRolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EliminarRolRequest) ProtoMessage() {}

func (x *EliminarRolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_seguridad_servicio_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EliminarRolRequest.ProtoReflect.Descriptor instead.
func (*EliminarRolRequest) Descriptor() ([]byte, []int) {
	return file_seguridad_servicio_proto_rawDescGZIP(), []int{18}
}

func (x *EliminarRolRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type EliminarRolResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mensaje       string                 `protobuf:"bytes,1,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EliminarRolResponse) Reset() {
	*x = EliminarRolResponse{}
	mi := &file_seguridad_servicio_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EliminarRolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EliminarRolResponse) ProtoMessage() {}

func (x *EliminarRolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_seguridad_servicio_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EliminarRolResponse.ProtoReflect.Descriptor instead.
func (*EliminarRolResponse) Descriptor() ([]byte, []int) {
	return file_seguridad_servicio_proto_rawDescGZIP(), []int{19}
}

func (x *EliminarRolResponse) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

type VincularPermisoRolRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RolId         string                 `protobuf:"bytes,1,opt,name=rol_id,json=rolId,proto3" json:"rol_id,omitempty"`
	Permisos      []string               `protobuf:"bytes,2,rep,name=permisos,proto3" json:"permisos,omitempty"` // Códigos de permisos a vincular
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VincularPermisoRolRequest) Reset() {
	*x = VincularPermisoRolRequest{}
	mi := &file_seguridad_servicio_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VincularPermisoRolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VincularPermisoRolRequest) ProtoMessage() {}

func (x *VincularPermisoRolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_seguridad_servicio_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VincularPermisoRolRequest.ProtoReflect.Descriptor instead.
func (*VincularPermisoRolRequest) Descriptor() ([]byte, []int) {
	return file_seguridad_servicio_proto_rawDescGZIP(), []int{20}
}

func (x *VincularPermisoRolRequest) GetRolId() string {
	if x != nil {
		return x.RolId
	}
	return ""
}

func (x *VincularPermisoRolRequest) GetPermisos() []string {
	if x != nil {
		return x.Permisos
	}
	return nil
}

type VincularPermisoRolResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vinculados    int32                  `protobuf:"varint,1,opt,name=vinculados,proto3" json:"vinculados,omitempty"`
	Mensaje       string                 `protobuf:"bytes,2,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VincularPermisoRolResponse) Reset() {
	*x = VincularPermisoRolResponse{}
	mi := &file_seguridad_servicio_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VincularPermisoRolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VincularPermisoRolResponse) ProtoMessage() {}

func (x *VincularPermisoRolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_seguridad_servicio_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VincularPermisoRolResponse.ProtoReflect.Descriptor instead.
func (*VincularPermisoRolResponse) Descriptor() ([]byte, []int) {
	return file_seguridad_servicio_proto_rawDescGZIP(), []int{21}
}

func (x *VincularPermisoRolResponse) GetVinculados() int32 {
	if x != nil {
		return x.Vinculados
	}
	return 0
}

func (x *VincularPermisoRolResponse) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

type DesvincularPermisoRolRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RolId         string                 `protobuf:"bytes,1,opt,name=rol_id,json=rolId,proto3" json:"rol_id,omitempty"`
	PermisoCodigo string                 `protobuf:"bytes,2,opt,name=permiso_codigo,json=permisoCodigo,proto3" json:"permiso_codigo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DesvincularPermisoRolRequest) Reset() {
	*x = DesvincularPermisoRolRequest{}
	mi := &file_seguridad_servicio_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DesvincularPermisoRolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DesvincularPermisoRolRequest) ProtoMessage() {}

func (x *DesvincularPermisoRolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_seguridad_servicio_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DesvincularPermisoRolRequest.ProtoReflect.Descriptor instead.
func (*DesvincularPermisoRolRequest) Descriptor() ([]byte, []int) {
	return file_seguridad_servicio_proto_rawDescGZIP(), []int{22}
}

func (x *DesvincularPermisoRolRequest) GetRolId() string {
	if x != nil {
		return x.RolId
	}
	return ""
}

func (x *DesvincularPermisoRolRequest) GetPermisoCodigo() string {
	if x != nil {
		return x.PermisoCodigo
	}
	return ""
}

type DesvincularPermisoRolResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mensaje       string                 `protobuf:"bytes,1,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DesvincularPermisoRolResponse) Reset() {
	*x = DesvincularPermisoRolResponse{}
	mi := &file_seguridad_servicio_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DesvincularPermisoRolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DesvincularPermisoRolResponse) ProtoMessage() {}

func (x *DesvincularPermisoRolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_seguridad_servicio_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DesvincularPermisoRolResponse.ProtoReflect.Descriptor instead.
func (*DesvincularPermisoRolResponse) Descriptor() ([]byte, []int) {
	return file_seguridad_servicio_proto_rawDescGZIP(), []int{23}
}

func (x *DesvincularPermisoRolResponse) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

type ListarPermisosRolRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RolId         string                 `protobuf:"bytes,1,opt,name=rol_id,json=rolId,proto3" json:"rol_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListarPermisosRolRequest) Reset() {
	*x = ListarPermisosRolRequest{}
	mi := &file_seguridad_servicio_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListarPermisosRolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListarPermisosRolRequest) ProtoMessage() {}

func (x *ListarPermisosRolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_seguridad_servicio_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListarPermisosRolRequest.ProtoReflect.Descriptor instead.
func (*ListarPermisosRolRequest) Descriptor() ([]byte, []int) {
	return file_seguridad_servicio_proto_rawDescGZIP(), []int{24}
}

func (x *ListarPermisosRolRequest) GetRolId() string {
	if x != nil {
		return x.RolId
	}
	return ""
}

type ListarPermisosRolResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Permisos      []string               `protobuf:"bytes,1,rep,name=permisos,proto3" json:"permisos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListarPermisosRolResponse) Reset() {
	*x = ListarPermisosRolResponse{}
	mi := &file_seguridad_servicio_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListarPermisosRolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListarPermisosRolResponse) ProtoMessage() {}

func (x *ListarPermisosRolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_seguridad_servicio_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListarPermisosRolResponse.ProtoReflect.Descriptor instead.
func (*ListarPermisosRolResponse) Descriptor() ([]byte, []int) {
	return file_seguridad_servicio_proto_rawDescGZIP(), []int{25}
}

func (x *ListarPermisosRolResponse) GetPermisos() []string {
	if x != nil {
		return x.Permisos
	}
	return nil
}

type CrearUsuarioRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	RolId         string                 `protobuf:"bytes,4,opt,name=rol_id,json=rolId,proto3" json:"rol_id,omitempty"`
	EsTecnico     bool                   `protobuf:"varint,5,opt,name=es_tecnico,json=esTecnico,proto3" json:"es_tecnico,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CrearUsuarioRequest) Reset() {
	*x = CrearUsuarioRequest{}
	mi := &file_seguridad_servicio_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrearUsuarioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrearUsuarioRequest) ProtoMessage() {}

func (x *CrearUsuarioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_seguridad_servicio_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrearUsuarioRequest.ProtoReflect.Descriptor instead.
func (*CrearUsuarioRequest) Descriptor() ([]byte, []int) {
	return file_seguridad_servicio_proto_rawDescGZIP(), []int{26}
}

func (x *CrearUsuarioRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CrearUsuarioRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CrearUsuarioRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CrearUsuarioRequest) GetRolId() string {
	if x != nil {
		return x.RolId
	}
	return ""
}

func (x *CrearUsuarioRequest) GetEsTecnico() bool {
	if x != nil {
		return x.EsTecnico
	}
	return false
}

type CrearUsuarioResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	RolId         string                 `protobuf:"bytes,4,opt,name=rol_id,json=rolId,proto3" json:"rol_id,omitempty"`
	EsTecnico     bool                   `protobuf:"varint,5,opt,name=es_tecnico,json=esTecnico,proto3" json:"es_tecnico,omitempty"`
	Estado        bool                   `protobuf:"varint,6,opt,name=estado,proto3" json:"estado,omitempty"`
	Mensaje       string                 `protobuf:"bytes,7,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CrearUsuarioResponse) Reset() {
	*x = CrearUsuarioResponse{}
	mi := &file_seguridad_servicio_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrearUsuarioResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrearUsuarioResponse) ProtoMessage() {}

func (x *CrearUsuarioResponse) ProtoReflect() protoreflect.Message {
	mi := &file_seguridad_servicio_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrearUsuarioResponse.ProtoReflect.Descriptor instead.
func (*CrearUsuarioResponse) Descriptor() ([]byte, []int) {
	return file_seguridad_servicio_proto_rawDescGZIP(), []int{27}
}

func (x *CrearUsuarioResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CrearUsuarioResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CrearUsuarioResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CrearUsuarioResponse) GetRolId() string {
	if x != nil {
		return x.RolId
	}
	return ""
}

func (x *CrearUsuarioResponse) GetEsTecnico() bool {
	if x != nil {
		return x.EsTecnico
	}
	return false
}

func (x *CrearUsuarioResponse) GetEstado() bool {
	if x != nil {
		return x.Estado
	}
	return false
}

func (x *CrearUsuarioResponse) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

type ListarUsuariosRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListarUsuariosRequest) Reset() {
	*x = ListarUsuariosRequest{}
	mi := &file_seguridad_servicio_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListarUsuariosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListarUsuariosRequest) ProtoMessage() {}

func (x *ListarUsuariosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_seguridad_servicio_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListarUsuariosRequest.ProtoReflect.Descriptor instead.
func (*ListarUsuariosRequest) Descriptor() ([]byte, []int) {
	return file_seguridad_servicio_proto_rawDescGZIP(), []int{28}
}

type UsuarioProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	RolId         string                 `protobuf:"bytes,4,opt,name=rol_id,json=rolId,proto3" json:"rol_id,omitempty"`
	RolNombre     string                 `protobuf:"bytes,5,opt,name=rol_nombre,json=rolNombre,proto3" json:"rol_nombre,omitempty"`
	EsTecnico     bool                   `protobuf:"varint,6,opt,name=es_tecnico,json=esTecnico,proto3" json:"es_tecnico,omitempty"`
	Estado        bool                   `protobuf:"varint,7,opt,name=estado,proto3" json:"estado,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsuarioProto) Reset() {
	*x = UsuarioProto{}
	mi := &file_seguridad_servicio_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsuarioProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsuarioProto) ProtoMessage() {}

func (x *UsuarioProto) ProtoReflect() protoreflect.Message {
	mi := &file_seguridad_servicio_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsuarioProto.ProtoReflect.Descriptor instead.
func (*UsuarioProto) Descriptor() ([]byte, []int) {
	return file_seguridad_servicio_proto_rawDescGZIP(), []int{29}
}

func (x *UsuarioProto) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UsuarioProto) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UsuarioProto) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UsuarioProto) GetRolId() string {
	if x != nil {
		return x.RolId
	}
	return ""
}

func (x *UsuarioProto) GetRolNombre() string {
	if x != nil {
		return x.RolNombre
	}
	return ""
}

func (x *UsuarioProto) GetEsTecnico() bool {
	if x != nil {
		return x.EsTecnico
	}
	return false
}

func (x *UsuarioProto) GetEstado() bool {
	if x != nil {
		return x.Estado
	}
	return false
}

type ListarUsuariosResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Usuarios      []*UsuarioProto        `protobuf:"bytes,1,rep,name=usuarios,proto3" json:"usuarios,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListarUsuariosResponse) Reset() {
	*x = ListarUsuariosResponse{}
	mi := &file_seguridad_servicio_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListarUsuariosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListarUsuariosResponse) ProtoMessage() {}

func (x *ListarUsuariosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_seguridad_servicio_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListarUsuariosResponse.ProtoReflect.Descriptor instead.
func (*ListarUsuariosResponse) Descriptor() ([]byte, []int) {
	return file_seguridad_servicio_proto_rawDescGZIP(), []int{30}
}

func (x *ListarUsuariosResponse) GetUsuarios() []*UsuarioProto {
	if x != nil {
		return x.Usuarios
	}
	return nil
}

type ObtenerUsuarioRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObtenerUsuarioRequest) Reset() {
	*x = ObtenerUsuarioRequest{}
	mi := &file_seguridad_servicio_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObtenerUsuarioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObtenerUsuarioRequest) ProtoMessage() {}

func (x *ObtenerUsuarioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_seguridad_servicio_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObtenerUsuarioRequest.ProtoReflect.Descriptor instead.
func (*ObtenerUsuarioRequest) Descriptor() ([]byte, []int) {
	return file_seguridad_servicio_proto_rawDescGZIP(), []int{31}
}

func (x *ObtenerUsuarioRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ObtenerUsuarioResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	RolId         string                 `protobuf:"bytes,4,opt,name=rol_id,json=rolId,proto3" json:"rol_id,omitempty"`
	RolNombre     string                 `protobuf:"bytes,5,opt,name=rol_nombre,json=rolNombre,proto3" json:"rol_nombre,omitempty"`
	EsTecnico     bool                   `protobuf:"varint,6,opt,name=es_tecnico,json=esTecnico,proto3" json:"es_tecnico,omitempty"`
	Estado        bool                   `protobuf:"varint,7,opt,name=estado,proto3" json:"estado,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObtenerUsuarioResponse) Reset() {
	*x = ObtenerUsuarioResponse{}
	mi := &file_seguridad_servicio_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObtenerUsuarioResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObtenerUsuarioResponse) ProtoMessage() {}

func (x *ObtenerUsuarioResponse) ProtoReflect() protoreflect.Message {
	mi := &file_seguridad_servicio_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObtenerUsuarioResponse.ProtoReflect.Descriptor instead.
func (*ObtenerUsuarioResponse) Descriptor() ([]byte, []int) {
	return file_seguridad_servicio_proto_rawDescGZIP(), []int{32}
}

func (x *ObtenerUsuarioResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ObtenerUsuarioResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ObtenerUsuarioResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ObtenerUsuarioResponse) GetRolId() string {
	if x != nil {
		return x.RolId
	}
	return ""
}

func (x *ObtenerUsuarioResponse) GetRolNombre() string {
	if x != nil {
		return x.RolNombre
	}
	return ""
}

func (x *ObtenerUsuarioResponse) GetEsTecnico() bool {
	if x != nil {
		return x.EsTecnico
	}
	return false
}

func (x *ObtenerUsuarioResponse) GetEstado() bool {
	if x != nil {
		return x.Estado
	}
	return false
}

type ActualizarUsuarioRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	RolId         string                 `protobuf:"bytes,3,opt,name=rol_id,json=rolId,proto3" json:"rol_id,omitempty"`
	EsTecnico     bool                   `protobuf:"varint,4,opt,name=es_tecnico,json=esTecnico,proto3" json:"es_tecnico,omitempty"`
	Estado        bool                   `protobuf:"varint,5,opt,name=estado,proto3" json:"estado,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActualizarUsuarioRequest) Reset() {
	*x = ActualizarUsuarioRequest{}
	mi := &file_seguridad_servicio_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActualizarUsuarioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActualizarUsuarioRequest) ProtoMessage() {}

func (x *ActualizarUsuarioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_seguridad_servicio_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActualizarUsuarioRequest.ProtoReflect.Descriptor instead.
func (*ActualizarUsuarioRequest) Descriptor() ([]byte, []int) {
	return file_seguridad_servicio_proto_rawDescGZIP(), []int{33}
}

func (x *ActualizarUsuarioRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ActualizarUsuarioRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ActualizarUsuarioRequest) GetRolId() string {
	if x != nil {
		return x.RolId
	}
	return ""
}

func (x *ActualizarUsuarioRequest) GetEsTecnico() bool {
	if x != nil {
		return x.EsTecnico
	}
	return false
}

func (x *ActualizarUsuarioRequest) GetEstado() bool {
	if x != nil {
		return x.Estado
	}
	return false
}

type ActualizarUsuarioResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	RolId         string                 `protobuf:"bytes,4,opt,name=rol_id,json=rolId,proto3" json:"rol_id,omitempty"`
	EsTecnico     bool                   `protobuf:"varint,5,opt,name=es_tecnico,json=esTecnico,proto3" json:"es_tecnico,omitempty"`
	Estado        bool                   `protobuf:"varint,6,opt,name=estado,proto3" json:"estado,omitempty"`
	Mensaje       string                 `protobuf:"bytes,7,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActualizarUsuarioResponse) Reset() {
	*x = ActualizarUsuarioResponse{}
	mi := &file_seguridad_servicio_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActualizarUsuarioResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActualizarUsuarioResponse) ProtoMessage() {}

func (x *ActualizarUsuarioResponse) ProtoReflect() protoreflect.Message {
	mi := &file_seguridad_servicio_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActualizarUsuarioResponse.ProtoReflect.Descriptor instead.
func (*ActualizarUsuarioResponse) Descriptor() ([]byte, []int) {
	return file_seguridad_servicio_proto_rawDescGZIP(), []int{34}
}

func (x *ActualizarUsuarioResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ActualizarUsuarioResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ActualizarUsuarioResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ActualizarUsuarioResponse) GetRolId() string {
	if x != nil {
		return x.RolId
	}
	return ""
}

func (x *ActualizarUsuarioResponse) GetEsTecnico() bool {
	if x != nil {
		return x.EsTecnico
	}
	return false
}

func (x *ActualizarUsuarioResponse) GetEstado() bool {
	if x != nil {
		return x.Estado
	}
	return false
}

func (x *ActualizarUsuarioResponse) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

type EliminarUsuarioRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EliminarUsuarioRequest) Reset() {
	*x = EliminarUsuarioRequest{}
	mi := &file_seguridad_servicio_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EliminarUsuarioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EliminarUsuarioRequest) ProtoMessage() {}

func (x *EliminarUsuarioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_seguridad_servicio_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EliminarUsuarioRequest.ProtoReflect.Descriptor instead.
func (*EliminarUsuarioRequest) Descriptor() ([]byte, []int) {
	return file_seguridad_servicio_proto_rawDescGZIP(), []int{35}
}

func (x *EliminarUsuarioRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type EliminarUsuarioResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mensaje       string                 `protobuf:"bytes,1,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EliminarUsuarioResponse) Reset() {
	*x = EliminarUsuarioResponse{}
	mi := &file_seguridad_servicio_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EliminarUsuarioResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EliminarUsuarioResponse) ProtoMessage() {}

func (x *EliminarUsuarioResponse) ProtoReflect() protoreflect.Message {
	mi := &file_seguridad_servicio_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EliminarUsuarioResponse.ProtoReflect.Descriptor instead.
func (*EliminarUsuarioResponse) Descriptor() ([]byte, []int) {
	return file_seguridad_servicio_proto_rawDescGZIP(), []int{36}
}

func (x *EliminarUsuarioResponse) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

var File_seguridad_servicio_proto protoreflect.FileDescriptor

const file_seguridad_servicio_proto_rawDesc = "" +
	"\n" +
	"\x18seguridad_servicio.proto\x12\adbgs.v1\x1a\x1cgoogle/api/annotations.proto\"\x17\n" +
	"\x15GetSetupStatusRequest\":\n" +
	"\x16GetSetupStatusResponse\x12 \n" +
	"\vinitialized\x18\x01 \x01(\bR\vinitialized\"b\n" +
	"\x12CreateSetupRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\"@\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\x95\x01\n" +
	"\rLoginResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x03 \x01(\x03R\texpiresIn\x12\x1d\n" +
	"\n" +
	"token_type\x18\x04 \x01(\tR\ttokenType\"+\n" +
	"\x13ValidarTokenRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\x80\x01\n" +
	"\x14ValidarTokenResponse\x12\x1b\n" +
	"\tes_valido\x18\x01 \x01(\bR\besValido\x12\x1d\n" +
	"\n" +
	"usuario_id\x18\x02 \x01(\tR\tusuarioId\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x10\n" +
	"\x03rol\x18\x04 \x01(\tR\x03rol\"j\n" +
	"\x17VerificarPermisoRequest\x12\x1d\n" +
	"\n" +
	"usuario_id\x18\x01 \x01(\tR\tusuarioId\x12\x18\n" +
	"\arecurso\x18\x02 \x01(\tR\arecurso\x12\x16\n" +
	"\x06accion\x18\x03 \x01(\tR\x06accion\"N\n" +
	"\x18VerificarPermisoResponse\x12\x1c\n" +
	"\tpermitido\x18\x01 \x01(\bR\tpermitido\x12\x14\n" +
	"\x05razon\x18\x02 \x01(\tR\x05razon\"K\n" +
	"\x0fCrearRolRequest\x12\x16\n" +
	"\x06nombre\x18\x01 \x01(\tR\x06nombre\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"v\n" +
	"\x10CrearRolResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06nombre\x18\x02 \x01(\tR\x06nombre\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x18\n" +
	"\amensaje\x18\x04 \x01(\tR\amensaje\"\x14\n" +
	"\x12ListarRolesRequest\"T\n" +
	"\bRolProto\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06nombre\x18\x02 \x01(\tR\x06nombre\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\">\n" +
	"\x13ListarRolesResponse\x12'\n" +
	"\x05roles\x18\x01 \x03(\v2\x11.dbgs.v1.RolProtoR\x05roles\"#\n" +
	"\x11ObtenerRolRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"^\n" +
	"\x12ObtenerRolResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06nombre\x18\x02 \x01(\tR\x06nombre\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"`\n" +
	"\x14ActualizarRolRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06nombre\x18\x02 \x01(\tR\x06nombre\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"{\n" +
	"\x15ActualizarRolResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06nombre\x18\x02 \x01(\tR\x06nombre\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x18\n" +
	"\amensaje\x18\x04 \x01(\tR\amensaje\"$\n" +
	"\x12EliminarRolRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"/\n" +
	"\x13EliminarRolResponse\x12\x18\n" +
	"\amensaje\x18\x01 \x01(\tR\amensaje\"N\n" +
	"\x19VincularPermisoRolRequest\x12\x15\n" +
	"\x06rol_id\x18\x01 \x01(\tR\x05rolId\x12\x1a\n" +
	"\bpermisos\x18\x02 \x03(\tR\bpermisos\"V\n" +
	"\x1aVincularPermisoRolResponse\x12\x1e\n" +
	"\n" +
	"vinculados\x18\x01 \x01(\x05R\n" +
	"vinculados\x12\x18\n" +
	"\amensaje\x18\x02 \x01(\tR\amensaje\"\\\n" +
	"\x1cDesvincularPermisoRolRequest\x12\x15\n" +
	"\x06rol_id\x18\x01 \x01(\tR\x05rolId\x12%\n" +
	"\x0epermiso_codigo\x18\x02 \x01(\tR\rpermisoCodigo\"9\n" +
	"\x1dDesvincularPermisoRolResponse\x12\x18\n" +
	"\amensaje\x18\x01 \x01(\tR\amensaje\"1\n" +
	"\x18ListarPermisosRolRequest\x12\x15\n" +
	"\x06rol_id\x18\x01 \x01(\tR\x05rolId\"7\n" +
	"\x19ListarPermisosRolResponse\x12\x1a\n" +
	"\bpermisos\x18\x01 \x03(\tR\bpermisos\"\x99\x01\n" +
	"\x13CrearUsuarioRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x15\n" +
	"\x06rol_id\x18\x04 \x01(\tR\x05rolId\x12\x1d\n" +
	"\n" +
	"es_tecnico\x18\x05 \x01(\bR\tesTecnico\"\xc0\x01\n" +
	"\x14CrearUsuarioResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x15\n" +
	"\x06rol_id\x18\x04 \x01(\tR\x05rolId\x12\x1d\n" +
	"\n" +
	"es_tecnico\x18\x05 \x01(\bR\tesTecnico\x12\x16\n" +
	"\x06estado\x18\x06 \x01(\bR\x06estado\x12\x18\n" +
	"\amensaje\x18\a \x01(\tR\amensaje\"\x17\n" +
	"\x15ListarUsuariosRequest\"\xbd\x01\n" +
	"\fUsuarioProto\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x15\n" +
	"\x06rol_id\x18\x04 \x01(\tR\x05rolId\x12\x1d\n" +
	"\n" +
	"rol_nombre\x18\x05 \x01(\tR\trolNombre\x12\x1d\n" +
	"\n" +
	"es_tecnico\x18\x06 \x01(\bR\tesTecnico\x12\x16\n" +
	"\x06estado\x18\a \x01(\bR\x06estado\"K\n" +
	"\x16ListarUsuariosResponse\x121\n" +
	"\busuarios\x18\x01 \x03(\v2\x15.dbgs.v1.UsuarioProtoR\busuarios\"'\n" +
	"\x15ObtenerUsuarioRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xc7\x01\n" +
	"\x16ObtenerUsuarioResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x15\n" +
	"\x06rol_id\x18\x04 \x01(\tR\x05rolId\x12\x1d\n" +
	"\n" +
	"rol_nombre\x18\x05 \x01(\tR\trolNombre\x12\x1d\n" +
	"\n" +
	"es_tecnico\x18\x06 \x01(\bR\tesTecnico\x12\x16\n" +
	"\x06estado\x18\a \x01(\bR\x06estado\"\x8e\x01\n" +
	"\x18ActualizarUsuarioRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x15\n" +
	"\x06rol_id\x18\x03 \x01(\tR\x05rolId\x12\x1d\n" +
	"\n" +
	"es_tecnico\x18\x04 \x01(\bR\tesTecnico\x12\x16\n" +
	"\x06estado\x18\x05 \x01(\bR\x06estado\"\xc5\x01\n" +
	"\x19ActualizarUsuarioResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x15\n" +
	"\x06rol_id\x18\x04 \x01(\tR\x05rolId\x12\x1d\n" +
	"\n" +
	"es_tecnico\x18\x05 \x01(\bR\tesTecnico\x12\x16\n" +
	"\x06estado\x18\x06 \x01(\bR\x06estado\x12\x18\n" +
	"\amensaje\x18\a \x01(\tR\amensaje\"(\n" +
	"\x16EliminarUsuarioRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"3\n" +
	"\x17EliminarUsuarioResponse\x12\x18\n" +
	"\amensaje\x18\x01 \x01(\tR\amensaje2\xea\x10\n" +
	"\x10SeguridadService\x12p\n" +
	"\x0eGetSetupStatus\x12\x1e.dbgs.v1.GetSetupStatusRequest\x1a\x1f.dbgs.v1.GetSetupStatusResponse\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/v1/auth/setup-status\x12]\n" +
	"\vCreateSetup\x12\x1b.dbgs.v1.CreateSetupRequest\x1a\x16.dbgs.v1.LoginResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/auth/setup\x12V\n" +
	"\x05Login\x12\x15.dbgs.v1.LoginRequest\x1a\x16.dbgs.v1.LoginResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/v1/seguridad/login\x12s\n" +
	"\fValidarToken\x12\x1c.dbgs.v1.ValidarTokenRequest\x1a\x1d.dbgs.v1.ValidarTokenResponse\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/v1/seguridad/validar-token\x12\x83\x01\n" +
	"\x10VerificarPermiso\x12 .dbgs.v1.VerificarPermisoRequest\x1a!.dbgs.v1.VerificarPermisoResponse\"*\x82\xd3\xe4\x93\x02$:\x01*\"\x1f/v1/seguridad/verificar-permiso\x12_\n" +
	"\bCrearRol\x12\x18.dbgs.v1.CrearRolRequest\x1a\x19.dbgs.v1.CrearRolResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/v1/seguridad/roles\x12e\n" +
	"\vListarRoles\x12\x1b.dbgs.v1.ListarRolesRequest\x1a\x1c.dbgs.v1.ListarRolesResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/v1/seguridad/roles\x12g\n" +
	"\n" +
	"ObtenerRol\x12\x1a.dbgs.v1.ObtenerRolRequest\x1a\x1b.dbgs.v1.ObtenerRolResponse\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/v1/seguridad/roles/{id}\x12s\n" +
	"\rActualizarRol\x12\x1d.dbgs.v1.ActualizarRolRequest\x1a\x1e.dbgs.v1.ActualizarRolResponse\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\x1a\x18/v1/seguridad/roles/{id}\x12j\n" +
	"\vEliminarRol\x12\x1b.dbgs.v1.EliminarRolRequest\x1a\x1c.dbgs.v1.EliminarRolResponse\" \x82\xd3\xe4\x93\x02\x1a*\x18/v1/seguridad/roles/{id}\x12\x8f\x01\n" +
	"\x12VincularPermisoRol\x12\".dbgs.v1.VincularPermisoRolRequest\x1a#.dbgs.v1.VincularPermisoRolResponse\"0\x82\xd3\xe4\x93\x02*:\x01*\"%/v1/seguridad/roles/{rol_id}/permisos\x12\xa6\x01\n" +
	"\x15DesvincularPermisoRol\x12%.dbgs.v1.DesvincularPermisoRolRequest\x1a&.dbgs.v1.DesvincularPermisoRolResponse\">\x82\xd3\xe4\x93\x028*6/v1/seguridad/roles/{rol_id}/permisos/{permiso_codigo}\x12\x89\x01\n" +
	"\x11ListarPermisosRol\x12!.dbgs.v1.ListarPermisosRolRequest\x1a\".dbgs.v1.ListarPermisosRolResponse\"-\x82\xd3\xe4\x93\x02'\x12%/v1/seguridad/roles/{rol_id}/permisos\x12n\n" +
	"\fCrearUsuario\x12\x1c.dbgs.v1.CrearUsuarioRequest\x1a\x1d.dbgs.v1.CrearUsuarioResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/v1/seguridad/usuarios\x12q\n" +
	"\x0eListarUsuarios\x12\x1e.dbgs.v1.ListarUsuariosRequest\x1a\x1f.dbgs.v1.ListarUsuariosResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/v1/seguridad/usuarios\x12v\n" +
	"\x0eObtenerUsuario\x12\x1e.dbgs.v1.ObtenerUsuarioRequest\x1a\x1f.dbgs.v1.ObtenerUsuarioResponse\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/v1/seguridad/usuarios/{id}\x12\x82\x01\n" +
	"\x11ActualizarUsuario\x12!.dbgs.v1.ActualizarUsuarioRequest\x1a\".dbgs.v1.ActualizarUsuarioResponse\"&\x82\xd3\xe4\x93\x02 :\x01*\x1a\x1b/v1/seguridad/usuarios/{id}\x12y\n" +
	"\x0fEliminarUsuario\x12\x1f.dbgs.v1.EliminarUsuarioRequest\x1a .dbgs.v1.EliminarUsuarioResponse\"#\x82\xd3\xe4\x93\x02\x1d*\x1b/v1/seguridad/usuarios/{id}B+Z)DBGS_SOBERANO_BACKEND/api/proto/v1;dbgsv1b\x06proto3"

var (
	file_seguridad_servicio_proto_rawDescOnce sync.Once
	file_seguridad_servicio_proto_rawDescData []byte
)

func file_seguridad_servicio_proto_rawDescGZIP() []byte {
	file_seguridad_servicio_proto_rawDescOnce.Do(func() {
		file_seguridad_servicio_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_seguridad_servicio_proto_rawDesc), len(file_seguridad_servicio_proto_rawDesc)))
	})
	return file_seguridad_servicio_proto_rawDescData
}

var file_seguridad_servicio_proto_msgTypes = make([]protoimpl.MessageInfo, 37)
var file_seguridad_servicio_proto_goTypes = []any{
	(*GetSetupStatusRequest)(nil),         // 0: dbgs.v1.GetSetupStatusRequest
	(*GetSetupStatusResponse)(nil),        // 1: dbgs.v1.GetSetupStatusResponse
	(*CreateSetupRequest)(nil),            // 2: dbgs.v1.CreateSetupRequest
	(*LoginRequest)(nil),                  // 3: dbgs.v1.LoginRequest
	(*LoginResponse)(nil),                 // 4: dbgs.v1.LoginResponse
	(*ValidarTokenRequest)(nil),           // 5: dbgs.v1.ValidarTokenRequest
	(*ValidarTokenResponse)(nil),          // 6: dbgs.v1.ValidarTokenResponse
	(*VerificarPermisoRequest)(nil),       // 7: dbgs.v1.VerificarPermisoRequest
	(*VerificarPermisoResponse)(nil),      // 8: dbgs.v1.VerificarPermisoResponse
	(*CrearRolRequest)(nil),               // 9: dbgs.v1.CrearRolRequest
	(*CrearRolResponse)(nil),              // 10: dbgs.v1.CrearRolResponse
	(*ListarRolesRequest)(nil),            // 11: dbgs.v1.ListarRolesRequest
	(*RolProto)(nil),                      // 12: dbgs.v1.RolProto
	(*ListarRolesResponse)(nil),           // 13: dbgs.v1.ListarRolesResponse
	(*ObtenerRolRequest)(nil),             // 14: dbgs.v1.ObtenerRolRequest
	(*ObtenerRolResponse)(nil),            // 15: dbgs.v1.ObtenerRolResponse
	(*ActualizarRolRequest)(nil),          // 16: dbgs.v1.ActualizarRolRequest
	(*ActualizarRolResponse)(nil),         // 17: dbgs.v1.ActualizarRolResponse
	(*EliminarRolRequest)(nil),            // 18: dbgs.v1.EliminarRolRequest
	(*EliminarRolResponse)(nil),           // 19: dbgs.v1.EliminarRolResponse
	(*VincularPermisoRolRequest)(nil),     // 20: dbgs.v1.VincularPermisoRolRequest
	(*VincularPermisoRolResponse)(nil),    // 21: dbgs.v1.VincularPermisoRolResponse
	(*DesvincularPermisoRolRequest)(nil),  // 22: dbgs.v1.DesvincularPermisoRolRequest
	(*DesvincularPermisoRolResponse)(nil), // 23: dbgs.v1.DesvincularPermisoRolResponse
	(*ListarPermisosRolRequest)(nil),      // 24: dbgs.v1.ListarPermisosRolRequest
	(*ListarPermisosRolResponse)(nil),     // 25: dbgs.v1.ListarPermisosRolResponse
	(*CrearUsuarioRequest)(nil),           // 26: dbgs.v1.CrearUsuarioRequest
	(*CrearUsuarioResponse)(nil),          // 27: dbgs.v1.CrearUsuarioResponse
	(*ListarUsuariosRequest)(nil),         // 28: dbgs.v1.ListarUsuariosRequest
	(*UsuarioProto)(nil),                  // 29: dbgs.v1.UsuarioProto
	(*ListarUsuariosResponse)(nil),        // 30: dbgs.v1.ListarUsuariosResponse
	(*ObtenerUsuarioRequest)(nil),         // 31: dbgs.v1.ObtenerUsuarioRequest
	(*ObtenerUsuarioResponse)(nil),        // 32: dbgs.v1.ObtenerUsuarioResponse
	(*ActualizarUsuarioRequest)(nil),      // 33: dbgs.v1.ActualizarUsuarioRequest
	(*ActualizarUsuarioResponse)(nil),     // 34: dbgs.v1.ActualizarUsuarioResponse
	(*EliminarUsuarioRequest)(nil),        // 35: dbgs.v1.EliminarUsuarioRequest
	(*EliminarUsuarioResponse)(nil),       // 36: dbgs.v1.EliminarUsuarioResponse
}
var file_seguridad_servicio_proto_depIdxs = []int32{
	12, // 0: dbgs.v1.ListarRolesResponse.roles:type_name -> dbgs.v1.RolProto
	29, // 1: dbgs.v1.ListarUsuariosResponse.usuarios:type_name -> dbgs.v1.UsuarioProto
	0,  // 2: dbgs.v1.SeguridadService.GetSetupStatus:input_type -> dbgs.v1.GetSetupStatusRequest
	2,  // 3: dbgs.v1.SeguridadService.CreateSetup:input_type -> dbgs.v1.CreateSetupRequest
	3,  // 4: dbgs.v1.SeguridadService.Login:input_type -> dbgs.v1.LoginRequest
	5,  // 5: dbgs.v1.SeguridadService.ValidarToken:input_type -> dbgs.v1.ValidarTokenRequest
	7,  // 6: dbgs.v1.SeguridadService.VerificarPermiso:input_type -> dbgs.v1.VerificarPermisoRequest
	9,  // 7: dbgs.v1.SeguridadService.CrearRol:input_type -> dbgs.v1.CrearRolRequest
	11, // 8: dbgs.v1.SeguridadService.ListarRoles:input_type -> dbgs.v1.ListarRolesRequest
	14, // 9: dbgs.v1.SeguridadService.ObtenerRol:input_type -> dbgs.v1.ObtenerRolRequest
	16, // 10: dbgs.v1.SeguridadService.ActualizarRol:input_type -> dbgs.v1.ActualizarRolRequest
	18, // 11: dbgs.v1.SeguridadService.EliminarRol:input_type -> dbgs.v1.EliminarRolRequest
	20, // 12: dbgs.v1.SeguridadService.VincularPermisoRol:input_type -> dbgs.v1.VincularPermisoRolRequest
	22, // 13: dbgs.v1.SeguridadService.DesvincularPermisoRol:input_type -> dbgs.v1.DesvincularPermisoRolRequest
	24, // 14: dbgs.v1.SeguridadService.ListarPermisosRol:input_type -> dbgs.v1.ListarPermisosRolRequest
	26, // 15: dbgs.v1.SeguridadService.CrearUsuario:input_type -> dbgs.v1.CrearUsuarioRequest
	28, // 16: dbgs.v1.SeguridadService.ListarUsuarios:input_type -> dbgs.v1.ListarUsuariosRequest
	31, // 17: dbgs.v1.SeguridadService.ObtenerUsuario:input_type -> dbgs.v1.ObtenerUsuarioRequest
	33, // 18: dbgs.v1.SeguridadService.ActualizarUsuario:input_type -> dbgs.v1.ActualizarUsuarioRequest
	35, // 19: dbgs.v1.SeguridadService.EliminarUsuario:input_type -> dbgs.v1.EliminarUsuarioRequest
	1,  // 20: dbgs.v1.SeguridadService.GetSetupStatus:output_type -> dbgs.v1.GetSetupStatusResponse
	4,  // 21: dbgs.v1.SeguridadService.CreateSetup:output_type -> dbgs.v1.LoginResponse
	4,  // 22: dbgs.v1.SeguridadService.Login:output_type -> dbgs.v1.LoginResponse
	6,  // 23: dbgs.v1.SeguridadService.ValidarToken:output_type -> dbgs.v1.ValidarTokenResponse
	8,  // 24: dbgs.v1.SeguridadService.VerificarPermiso:output_type -> dbgs.v1.VerificarPermisoResponse
	10, // 25: dbgs.v1.SeguridadService.CrearRol:output_type -> dbgs.v1.CrearRolResponse
	13, // 26: dbgs.v1.SeguridadService.ListarRoles:output_type -> dbgs.v1.ListarRolesResponse
	15, // 27: dbgs.v1.SeguridadService.ObtenerRol:output_type -> dbgs.v1.ObtenerRolResponse
	17, // 28: dbgs.v1.SeguridadService.ActualizarRol:output_type -> dbgs.v1.ActualizarRolResponse
	19, // 29: dbgs.v1.SeguridadService.EliminarRol:output_type -> dbgs.v1.EliminarRolResponse
	21, // 30: dbgs.v1.SeguridadService.VincularPermisoRol:output_type -> dbgs.v1.VincularPermisoRolResponse
	23, // 31: dbgs.v1.SeguridadService.DesvincularPermisoRol:output_type -> dbgs.v1.DesvincularPermisoRolResponse
	25, // 32: dbgs.v1.SeguridadService.ListarPermisosRol:output_type -> dbgs.v1.ListarPermisosRolResponse
	27, // 33: dbgs.v1.SeguridadService.CrearUsuario:output_type -> dbgs.v1.CrearUsuarioResponse
	30, // 34: dbgs.v1.SeguridadService.ListarUsuarios:output_type -> dbgs.v1.ListarUsuariosResponse
	32, // 35: dbgs.v1.SeguridadService.ObtenerUsuario:output_type -> dbgs.v1.ObtenerUsuarioResponse
	34, // 36: dbgs.v1.SeguridadService.ActualizarUsuario:output_type -> dbgs.v1.ActualizarUsuarioResponse
	36, // 37: dbgs.v1.SeguridadService.EliminarUsuario:output_type -> dbgs.v1.EliminarUsuarioResponse
	20, // [20:38] is the sub-list for method output_type
	2,  // [2:20] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_seguridad_servicio_proto_init() }
func file_seguridad_servicio_proto_init() {
	if File_seguridad_servicio_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_seguridad_servicio_proto_rawDesc), len(file_seguridad_servicio_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   37,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_seguridad_servicio_proto_goTypes,
		DependencyIndexes: file_seguridad_servicio_proto_depIdxs,
		MessageInfos:      file_seguridad_servicio_proto_msgTypes,
	}.Build()
	File_seguridad_servicio_proto = out.File
	file_seguridad_servicio_proto_goTypes = nil
	file_seguridad_servicio_proto_depIdxs = nil
}
