// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: sistema_servicio.proto

package dbgsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SistemaService_GetHealth_FullMethodName  = "/dbgs.v1.SistemaService/GetHealth"
	SistemaService_GetVersion_FullMethodName = "/dbgs.v1.SistemaService/GetVersion"
)

// SistemaServiceClient is the client API for SistemaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Servicio de Diagnóstico y Estado del Sistema
// NOTA: Estos endpoints NO requieren autenticación JWT.
type SistemaServiceClient interface {
	// Verifica la conectividad con los componentes críticos (ej. PostgreSQL)
	GetHealth(ctx context.Context, in *GetHealthRequest, opts ...grpc.CallOption) (*GetHealthResponse, error)
	// Obtiene la versión del motor, el commit de compilación y el entorno
	GetVersion(ctx context.Context, in *GetVersionRequest, opts ...grpc.CallOption) (*GetVersionResponse, error)
}

type sistemaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSistemaServiceClient(cc grpc.ClientConnInterface) SistemaServiceClient {
	return &sistemaServiceClient{cc}
}

func (c *sistemaServiceClient) GetHealth(ctx context.Context, in *GetHealthRequest, opts ...grpc.CallOption) (*GetHealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHealthResponse)
	err := c.cc.Invoke(ctx, SistemaService_GetHealth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sistemaServiceClient) GetVersion(ctx context.Context, in *GetVersionRequest, opts ...grpc.CallOption) (*GetVersionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVersionResponse)
	err := c.cc.Invoke(ctx, SistemaService_GetVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SistemaServiceServer is the server API for SistemaService service.
// All implementations must embed UnimplementedSistemaServiceServer
// for forward compatibility.
//
// Servicio de Diagnóstico y Estado del Sistema
// NOTA: Estos endpoints NO requieren autenticación JWT.
type SistemaServiceServer interface {
	// Verifica la conectividad con los componentes críticos (ej. PostgreSQL)
	GetHealth(context.Context, *GetHealthRequest) (*GetHealthResponse, error)
	// Obtiene la versión del motor, el commit de compilación y el entorno
	GetVersion(context.Context, *GetVersionRequest) (*GetVersionResponse, error)
	mustEmbedUnimplementedSistemaServiceServer()
}

// UnimplementedSistemaServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSistemaServiceServer struct{}

func (UnimplementedSistemaServiceServer) GetHealth(context.Context, *GetHealthRequest) (*GetHealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHealth not implemented")
}
func (UnimplementedSistemaServiceServer) GetVersion(context.Context, *GetVersionRequest) (*GetVersionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVersion not implemented")
}
func (UnimplementedSistemaServiceServer) mustEmbedUnimplementedSistemaServiceServer() {}
func (UnimplementedSistemaServiceServer) testEmbeddedByValue()                        {}

// UnsafeSistemaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SistemaServiceServer will
// result in compilation errors.
type UnsafeSistemaServiceServer interface {
	mustEmbedUnimplementedSistemaServiceServer()
}

func RegisterSistemaServiceServer(s grpc.ServiceRegistrar, srv SistemaServiceServer) {
	// If the following call panics, it indicates UnimplementedSistemaServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SistemaService_ServiceDesc, srv)
}

func _SistemaService_GetHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SistemaServiceServer).GetHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SistemaService_GetHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SistemaServiceServer).GetHealth(ctx, req.(*GetHealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SistemaService_GetVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SistemaServiceServer).GetVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SistemaService_GetVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SistemaServiceServer).GetVersion(ctx, req.(*GetVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SistemaService_ServiceDesc is the grpc.ServiceDesc for SistemaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SistemaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dbgs.v1.SistemaService",
	HandlerType: (*SistemaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetHealth",
			Handler:    _SistemaService_GetHealth_Handler,
		},
		{
			MethodName: "GetVersion",
			Handler:    _SistemaService_GetVersion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sistema_servicio.proto",
}
